-- Example: shape of an envelope insert as produced by
-- writeMeasurementArtifactEnvelope() in
-- supabase/functions/_shared/mskill/artifacts.ts.
--
-- NOTE: This file is illustrative only. It has NOT been executed against
-- the database. Bind parameters are shown as :placeholder.

INSERT INTO public.mskill_artifacts (
  tenant_id,
  mskill_request_id,
  mskill_job_id,
  mskill_run_id,
  request_hash,
  artifact_type,
  storage_path,
  source_url,
  byte_size,
  metadata,
  artifact_id,
  schema_version,
  envelope_version,
  parent_artifact_ids,
  stage,
  source_skill,
  producer_kind,
  producer,
  status,
  coordinate_frame,
  units,
  geometry,
  data,
  quality,
  validation,
  lineage,
  display,
  storage_block,
  validation_status,
  validation_confidence,
  export_allowed,
  report_allowed,
  envelope
) VALUES (
  :tenant_id,
  :mskill_request_id,
  :mskill_job_id,
  :mskill_run_id,
  :request_hash,
  'roof_planes',
  'mskill/<tenant>/<job>/roof_planes.json',
  NULL,
  12345,
  '{}'::jsonb,
  :artifact_uuid,
  '1.0.0',
  1,
  ARRAY[:dsm_artifact_uuid, :roof_points_artifact_uuid]::uuid[],
  'geometry',
  'fit_roof_planes',
  'worker',
  '{"kind":"worker","name":"pitch-measure-worker","version":"0.3.1"}'::jsonb,
  'complete',
  '{"type":"geographic","crs":"EPSG:4326","status":"complete"}'::jsonb,
  '{"length":"m","area":"m2","angle":"deg"}'::jsonb,
  '{"type":"feature_collection","feature_count":7}'::jsonb,
  '{"planes":[/* ... */]}'::jsonb,
  '{"score":0.91,"coverage":0.88}'::jsonb,
  '{"validation_status":"pending","confidence":null,"checks":[]}'::jsonb,
  '{"parent_artifacts":[:dsm_artifact_uuid,:roof_points_artifact_uuid],"pipeline_run_id":":run_id"}'::jsonb,
  '{"map_visibility":"on_zoom","report_visibility":"internal"}'::jsonb,
  '{"type":"supabase_storage","bucket":"mskill","path":"<...>","byte_size":12345}'::jsonb,
  'pending',
  NULL,
  false,
  false,
  :full_envelope_jsonb
);

-- Issues are written separately, one row per warning/error/blocker.
INSERT INTO public.mskill_artifact_issues (
  tenant_id,
  mskill_request_id,
  mskill_job_id,
  mskill_run_id,
  artifact_id,
  mskill_artifact_id,
  severity,
  code,
  message,
  object_type,
  object_id,
  source_skill,
  blocking,
  suggested_fix,
  metadata
) VALUES (
  :tenant_id,
  :mskill_request_id,
  :mskill_job_id,
  :mskill_run_id,
  :artifact_uuid,
  :mskill_artifact_row_id,
  'warning',
  'plane_coverage_low',
  'Plane 3 coverage 0.62 below 0.70 floor.',
  'plane',
  'plane_3',
  'fit_roof_planes',
  false,
  'Re-run with denser DSM or relaxed RANSAC threshold.',
  '{"coverage":0.62,"threshold":0.70}'::jsonb
);
