import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

interface LaborItem {
  id: string;
  item_name: string;
  qty: number;
  unit: string;
  unit_cost: number;
  line_total: number;
}

interface LaborOrderExportProps {
  estimateId: string;
  laborItems: LaborItem[];
  totalAmount: number;
  customerName?: string;
  projectAddress?: string;
}

export function LaborOrderExport({ 
  estimateId, 
  laborItems, 
  totalAmount,
  customerName,
  projectAddress 
}: LaborOrderExportProps) {
  const { toast } = useToast();

  const generatePDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      let yPos = 20;

      // Header
      doc.setFillColor(52, 211, 153); // Green color for labor
      doc.rect(0, 0, pageWidth, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.text('LABOR ORDER', margin, 25);
      doc.setFontSize(12);
      doc.text(`Estimate #${estimateId.slice(-8).toUpperCase()}`, margin, 35);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin - 50, 35);

      yPos = 55;
      doc.setTextColor(0, 0, 0);
      
      // Project Info
      if (customerName || projectAddress) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Project Information', margin, yPos);
        yPos += 10;
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        if (customerName) {
          doc.text(`Customer: ${customerName}`, margin, yPos);
          yPos += 6;
        }
        if (projectAddress) {
          doc.text(`Address: ${projectAddress}`, margin, yPos);
          yPos += 6;
        }
        yPos += 10;
      }

      // Job Site Address - PROMINENT SECTION
      if (projectAddress) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Job Site Address', margin, yPos);
        yPos += 8;

        doc.setFillColor(236, 253, 245); // Light green background
        doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 16, 'F');
        doc.setDrawColor(52, 211, 153); // Green border
        doc.rect(margin, yPos - 4, pageWidth - 2 * margin, 16, 'S');
        
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(6, 95, 70); // Dark green text
        doc.text(projectAddress, margin + 5, yPos + 5);
        doc.setTextColor(0, 0, 0); // Reset text color
        
        yPos += 22;
      }

      // Labor Items Table
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Labor Items', margin, yPos);
      yPos += 10;

      // Table headers
      doc.setFillColor(249, 250, 251);
      doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Description', margin + 2, yPos);
      doc.text('Qty', pageWidth - 100, yPos);
      doc.text('Unit', pageWidth - 80, yPos);
      doc.text('Rate', pageWidth - 55, yPos);
      doc.text('Total', pageWidth - 30, yPos);
      yPos += 10;

      // Table rows
      doc.setFont('helvetica', 'normal');
      laborItems.forEach((item) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        
        const desc = item.item_name.length > 40 
          ? item.item_name.substring(0, 40) + '...' 
          : item.item_name;
        
        doc.text(desc, margin + 2, yPos);
        doc.text(item.qty.toFixed(1), pageWidth - 100, yPos);
        doc.text(item.unit, pageWidth - 80, yPos);
        doc.text(`$${item.unit_cost.toFixed(2)}`, pageWidth - 55, yPos);
        doc.text(`$${item.line_total.toFixed(2)}`, pageWidth - 30, yPos);
        yPos += 8;
      });

      // Total
      yPos += 5;
      doc.setDrawColor(229, 231, 235);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 10;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('Total Labor Cost:', pageWidth - 80, yPos);
      doc.setTextColor(52, 211, 153);
      doc.text(`$${totalAmount.toFixed(2)}`, pageWidth - 30, yPos);

      // Footer
      const footerY = doc.internal.pageSize.getHeight() - 20;
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text('Generated by PITCH CRM - Labor Orders System', pageWidth / 2, footerY, { align: 'center' });
      doc.text(new Date().toLocaleString(), pageWidth / 2, footerY + 5, { align: 'center' });

      return doc;
    } catch (error) {
      console.error('Error generating Labor PDF:', error);
      toast({
        title: "PDF Generation Failed",
        description: "Could not generate the labor order PDF.",
        variant: "destructive"
      });
      return null;
    }
  };

  const handleDownloadPDF = () => {
    const doc = generatePDF();
    if (doc) {
      doc.save(`Labor_Order_${estimateId.slice(-8)}_${new Date().toISOString().split('T')[0]}.pdf`);
      toast({
        title: "PDF Downloaded",
        description: "Labor order has been saved."
      });
    }
  };

  return (
    <Button
      variant="outline"
      size="sm"
      onClick={handleDownloadPDF}
      className="gap-2"
      disabled={laborItems.length === 0}
    >
      <Download className="h-4 w-4" />
      Export Labor Order
    </Button>
  );
}
