import { Button } from "@/components/ui/button";
import { Download, Mail, FileText } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useMaterialOrderEmail } from "@/hooks/useMaterialOrderEmail";
import jsPDF from "jspdf";

interface MaterialOrderExportProps {
  order: any;
  items: any[];
}

export function MaterialOrderExport({ order, items }: MaterialOrderExportProps) {
  const { toast } = useToast();
  const { sendOrderEmail, sending } = useMaterialOrderEmail();

  const generatePDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      let yPos = 20;

      // Header
      doc.setFillColor(102, 126, 234);
      doc.rect(0, 0, pageWidth, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.text('PURCHASE ORDER', margin, 25);
      doc.setFontSize(12);
      doc.text(`PO# ${order.po_number}`, margin, 35);

      yPos = 55;
      doc.setTextColor(0, 0, 0);
      
      // Vendor Info
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Vendor Information', margin, yPos);
      yPos += 10;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`${order.vendors?.name || 'N/A'}`, margin, yPos);
      yPos += 6;
      if (order.vendors?.contact_name) {
        doc.text(`Contact: ${order.vendors.contact_name}`, margin, yPos);
        yPos += 6;
      }
      if (order.vendors?.email) {
        doc.text(`Email: ${order.vendors.email}`, margin, yPos);
        yPos += 6;
      }
      if (order.vendors?.phone) {
        doc.text(`Phone: ${order.vendors.phone}`, margin, yPos);
        yPos += 6;
      }

      yPos += 10;

      // Order Details
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Order Details', margin, yPos);
      yPos += 10;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text(`Status: ${order.status.toUpperCase()}`, margin, yPos);
      yPos += 6;
      doc.text(`Order Date: ${new Date(order.order_date).toLocaleDateString()}`, margin, yPos);
      yPos += 6;
      if (order.required_date) {
        doc.text(`Required Date: ${new Date(order.required_date).toLocaleDateString()}`, margin, yPos);
        yPos += 6;
      }
      if (order.branch_code) {
        doc.text(`Branch Code: ${order.branch_code}`, margin, yPos);
        yPos += 6;
      }
      if (order.delivery_address) {
        doc.text(`Delivery: ${order.delivery_address}`, margin, yPos);
        yPos += 6;
      }

      yPos += 10;

      // Items Table
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Order Items', margin, yPos);
      yPos += 10;

      // Table headers
      doc.setFillColor(249, 250, 251);
      doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 8, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('Description', margin + 2, yPos);
      doc.text('Qty', pageWidth - 90, yPos);
      doc.text('Unit Price', pageWidth - 65, yPos);
      doc.text('Total', pageWidth - 35, yPos);
      yPos += 10;

      // Table rows
      doc.setFont('helvetica', 'normal');
      items.forEach((item) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        
        const desc = item.item_description.length > 45 
          ? item.item_description.substring(0, 45) + '...' 
          : item.item_description;
        
        doc.text(desc, margin + 2, yPos);
        doc.text(item.quantity.toString(), pageWidth - 90, yPos);
        doc.text(`$${item.unit_price?.toFixed(2) || '0.00'}`, pageWidth - 65, yPos);
        doc.text(`$${item.total_price?.toFixed(2) || '0.00'}`, pageWidth - 35, yPos);
        yPos += 8;
      });

      // Total
      yPos += 5;
      doc.setDrawColor(229, 231, 235);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 10;
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.text('Total Amount:', pageWidth - 80, yPos);
      doc.setTextColor(102, 126, 234);
      doc.text(`$${order.total_amount?.toFixed(2) || '0.00'}`, pageWidth - 35, yPos);

      // Notes
      if (order.notes) {
        yPos += 15;
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text('Notes:', margin, yPos);
        yPos += 6;
        doc.setFont('helvetica', 'normal');
        const splitNotes = doc.splitTextToSize(order.notes, pageWidth - 2 * margin);
        doc.text(splitNotes, margin, yPos);
      }

      // Footer
      const footerY = doc.internal.pageSize.getHeight() - 20;
      doc.setFontSize(8);
      doc.setTextColor(107, 114, 128);
      doc.text('Generated by PITCH CRM - Material Orders System', pageWidth / 2, footerY, { align: 'center' });
      doc.text(new Date().toLocaleString(), pageWidth / 2, footerY + 5, { align: 'center' });

      return doc;
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast({
        title: "PDF Generation Failed",
        description: "Could not generate the PDF document.",
        variant: "destructive"
      });
      return null;
    }
  };

  const handleDownloadPDF = () => {
    const doc = generatePDF();
    if (doc) {
      doc.save(`PO_${order.po_number}_${new Date().toISOString().split('T')[0]}.pdf`);
      toast({
        title: "PDF Downloaded",
        description: `Purchase order ${order.po_number} has been saved.`
      });
    }
  };

  const handleEmailVendor = async () => {
    try {
      await sendOrderEmail({
        orderId: order.id,
        action: 'submit'
      });
    } catch (error) {
      console.error('Failed to send email:', error);
    }
  };

  return (
    <div className="flex gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handleDownloadPDF}
        className="gap-2"
      >
        <Download className="h-4 w-4" />
        Download PDF
      </Button>
      <Button
        variant="outline"
        size="sm"
        onClick={handleEmailVendor}
        disabled={sending || !order.vendors?.email}
        className="gap-2"
      >
        <Mail className="h-4 w-4" />
        {sending ? 'Sending...' : 'Email Vendor'}
      </Button>
    </div>
  );
}
