import { useState, useCallback } from 'react';
import jsPDF from 'jspdf';
import { toast } from 'sonner';
import { INSPECTION_STEPS } from './inspectionSteps';

interface StepData {
  stepId: string;
  photoUrl: string | null;
  notes: string;
  completedAt: string | null;
  skipped?: boolean;
}

interface InspectionReportData {
  stepsData: StepData[];
  propertyAddress?: string;
  inspectorName?: string;
  inspectionDate?: string;
  status?: string;
  companyName?: string;
}

// Layout constants (mm)
const PAGE_W = 215.9;
const PAGE_H = 279.4;
const MARGIN = 15;
const CONTENT_W = PAGE_W - MARGIN * 2;
const PHOTO_W = 75;
const PHOTO_H = 56;
const FOOTER_H = 12;
const MAX_Y = PAGE_H - MARGIN - FOOTER_H;

async function fetchImageAsBase64(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) return null;
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function addFooter(pdf: jsPDF, pageNum: number, totalPages: number, timestamp: string) {
  const y = PAGE_H - MARGIN;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(MARGIN, y - 4, PAGE_W - MARGIN, y - 4);
  pdf.setFontSize(8);
  pdf.setTextColor(130, 130, 130);
  pdf.text(`Page ${pageNum} of ${totalPages}`, MARGIN, y);
  pdf.text(`Generated by PITCH CRM  •  ${timestamp}`, PAGE_W - MARGIN, y, { align: 'right' });
}

function ensureSpace(pdf: jsPDF, y: number, needed: number, pageCount: { value: number }): number {
  if (y + needed > MAX_Y) {
    pdf.addPage();
    pageCount.value += 1;
    return MARGIN;
  }
  return y;
}

export function useInspectionReportPDF() {
  const [generating, setGenerating] = useState(false);

  const generateReport = useCallback(async (data: InspectionReportData): Promise<Blob | null> => {
    setGenerating(true);
    try {
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
      const pageCount = { value: 1 };
      const timestamp = new Date().toLocaleString();
      const completedCount = data.stepsData.filter((s) => s.photoUrl).length;
      const skippedCount = data.stepsData.filter((s) => s.skipped && !s.photoUrl).length;

      // ── Cover / Header ──
      let y = MARGIN;

      // Title block
      pdf.setFillColor(24, 24, 27); // zinc-900
      pdf.rect(0, 0, PAGE_W, 52, 'F');

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(22);
      pdf.setFont('helvetica', 'bold');
      pdf.text('PROPERTY INSPECTION', MARGIN, y + 14);
      pdf.setFontSize(16);
      pdf.text('REPORT', MARGIN, y + 22);

      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      if (data.companyName) {
        pdf.text(data.companyName, MARGIN, y + 32);
      }

      // Right-aligned metadata
      const metaX = PAGE_W - MARGIN;
      pdf.setFontSize(9);
      let metaY = y + 14;
      if (data.inspectionDate) {
        pdf.text(`Date: ${data.inspectionDate}`, metaX, metaY, { align: 'right' });
        metaY += 5;
      }
      if (data.inspectorName) {
        pdf.text(`Inspector: ${data.inspectorName}`, metaX, metaY, { align: 'right' });
        metaY += 5;
      }
      if (data.status) {
        pdf.text(`Status: ${data.status}`, metaX, metaY, { align: 'right' });
      }

      y = 60;

      // Property address
      if (data.propertyAddress) {
        pdf.setTextColor(60, 60, 60);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Property:', MARGIN, y);
        pdf.setFont('helvetica', 'normal');
        pdf.text(data.propertyAddress, MARGIN + 22, y);
        y += 10;
      }

      // Summary box
      pdf.setFillColor(245, 245, 245);
      pdf.roundedRect(MARGIN, y, CONTENT_W, 16, 2, 2, 'F');
      pdf.setFontSize(10);
      pdf.setTextColor(80, 80, 80);
      pdf.setFont('helvetica', 'bold');
      pdf.text('SUMMARY', MARGIN + 4, y + 6);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      pdf.text(
        `${INSPECTION_STEPS.length} steps  •  ${completedCount} completed  •  ${skippedCount} skipped`,
        MARGIN + 4,
        y + 12
      );
      y += 22;

      // ── Fetch all photos in parallel ──
      toast.info('Loading inspection photos...');
      const photoPromises = data.stepsData.map((s) =>
        s.photoUrl ? fetchImageAsBase64(s.photoUrl) : Promise.resolve(null)
      );
      const photos = await Promise.all(photoPromises);
      toast.info('Building PDF...');

      // ── Render each step ──
      for (let i = 0; i < INSPECTION_STEPS.length; i++) {
        const step = INSPECTION_STEPS[i];
        const stepData = data.stepsData[i];
        const photo = photos[i];
        const hasPhoto = !!photo;
        const stepHeight = hasPhoto ? Math.max(PHOTO_H + 8, 30) : 20;
        const notesLines = stepData?.notes
          ? pdf.splitTextToSize(stepData.notes, hasPhoto ? CONTENT_W - PHOTO_W - 10 : CONTENT_W - 4)
          : [];
        const totalNeeded = stepHeight + notesLines.length * 4 + 8;

        y = ensureSpace(pdf, y, totalNeeded, pageCount);

        // Step header bar
        pdf.setFillColor(240, 240, 240);
        pdf.roundedRect(MARGIN, y, CONTENT_W, 8, 1, 1, 'F');
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(40, 40, 40);
        pdf.text(`${i + 1}. ${step.title.toUpperCase()}`, MARGIN + 3, y + 5.5);

        if (stepData?.skipped && !hasPhoto) {
          pdf.setFontSize(8);
          pdf.setTextColor(180, 100, 0);
          pdf.text('SKIPPED', PAGE_W - MARGIN - 3, y + 5.5, { align: 'right' });
        }
        y += 11;

        // Photo + notes side by side
        if (hasPhoto) {
          try {
            pdf.addImage(photo!, 'JPEG', MARGIN, y, PHOTO_W, PHOTO_H);
          } catch {
            // fallback: draw placeholder
            pdf.setFillColor(230, 230, 230);
            pdf.rect(MARGIN, y, PHOTO_W, PHOTO_H, 'F');
            pdf.setFontSize(8);
            pdf.setTextColor(150, 150, 150);
            pdf.text('Photo unavailable', MARGIN + PHOTO_W / 2, y + PHOTO_H / 2, { align: 'center' });
          }

          // Notes beside photo
          if (notesLines.length > 0) {
            const notesX = MARGIN + PHOTO_W + 5;
            pdf.setFontSize(8);
            pdf.setFont('helvetica', 'bold');
            pdf.setTextColor(100, 100, 100);
            pdf.text('Notes:', notesX, y + 5);
            pdf.setFont('helvetica', 'normal');
            pdf.setTextColor(60, 60, 60);
            pdf.setFontSize(9);
            let noteY = y + 10;
            for (const line of notesLines) {
              if (noteY > MAX_Y) break;
              pdf.text(line, notesX, noteY);
              noteY += 4;
            }
          }

          y += PHOTO_H + 4;
        } else if (notesLines.length > 0) {
          // Notes only (no photo)
          pdf.setFontSize(9);
          pdf.setTextColor(60, 60, 60);
          for (const line of notesLines) {
            pdf.text(line, MARGIN + 3, y);
            y += 4;
          }
        }

        y += 4; // spacing between steps
      }

      // ── Add footers to all pages ──
      const total = pageCount.value;
      for (let p = 1; p <= total; p++) {
        pdf.setPage(p);
        addFooter(pdf, p, total, timestamp);
      }

      const blob = pdf.output('blob');
      toast.success('Inspection report generated!');
      return blob;
    } catch (err: any) {
      console.error('PDF generation error:', err);
      toast.error('Failed to generate report');
      return null;
    } finally {
      setGenerating(false);
    }
  }, []);

  const downloadReport = useCallback(
    async (data: InspectionReportData, filename?: string) => {
      const blob = await generateReport(data);
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename || `inspection-report-${Date.now()}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    },
    [generateReport]
  );

  return { generateReport, downloadReport, generating };
}
