import { useState, useCallback } from 'react';
import jsPDF from 'jspdf';
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';
import { INSPECTION_STEPS } from './inspectionSteps';

interface StepData {
  stepId: string;
  photoUrls: string[];
  notes: string;
  completedAt: string | null;
  skipped?: boolean;
}

interface InspectionReportData {
  stepsData: StepData[];
  propertyAddress?: string;
  inspectorName?: string;
  inspectionDate?: string;
  status?: string;
  companyName?: string;
}

// Layout constants (mm)
const PAGE_W = 215.9;
const PAGE_H = 279.4;
const MARGIN = 15;
const CONTENT_W = PAGE_W - MARGIN * 2;
const PHOTO_W = 75;
const PHOTO_H = 56;
const FOOTER_H = 12;
const MAX_Y = PAGE_H - MARGIN - FOOTER_H;

async function fetchImageAsBase64(url: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) return null;
    const blob = await response.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

async function polishNotes(
  stepsData: StepData[]
): Promise<Map<number, string>> {
  const polished = new Map<number, string>();
  const toPolish = stepsData
    .map((s, i) => ({ index: i, notes: s.notes }))
    .filter((s) => s.notes && s.notes.trim().length > 0);

  if (toPolish.length === 0) return polished;

  const results = await Promise.allSettled(
    toPolish.map(async ({ index, notes }) => {
      const step = INSPECTION_STEPS[index];
      const { data, error } = await supabase.functions.invoke('polish-inspection-notes', {
        body: { notes, stepTitle: step.title, stepDescription: step.description },
      });
      if (error) throw error;
      return { index, text: data?.polished || notes };
    })
  );

  for (const r of results) {
    if (r.status === 'fulfilled') {
      polished.set(r.value.index, r.value.text);
    }
  }
  return polished;
}

function addFooter(pdf: jsPDF, pageNum: number, totalPages: number, timestamp: string) {
  const y = PAGE_H - MARGIN;
  pdf.setDrawColor(200, 200, 200);
  pdf.line(MARGIN, y - 4, PAGE_W - MARGIN, y - 4);
  pdf.setFontSize(8);
  pdf.setTextColor(130, 130, 130);
  pdf.text(`Page ${pageNum} of ${totalPages}`, MARGIN, y);
  pdf.text(`Generated by PITCH CRM  •  ${timestamp}`, PAGE_W - MARGIN, y, { align: 'right' });
}

function ensureSpace(pdf: jsPDF, y: number, needed: number, pageCount: { value: number }): number {
  if (y + needed > MAX_Y) {
    pdf.addPage();
    pageCount.value += 1;
    return MARGIN;
  }
  return y;
}

export function useInspectionReportPDF() {
  const [generating, setGenerating] = useState(false);

  const generateReport = useCallback(async (data: InspectionReportData): Promise<Blob | null> => {
    setGenerating(true);
    try {
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
      const pageCount = { value: 1 };
      const timestamp = new Date().toLocaleString();
      const completedCount = data.stepsData.filter((s) => s.photoUrls.length > 0).length;
      const skippedCount = data.stepsData.filter((s) => s.skipped && s.photoUrls.length === 0).length;

      // ── Cover / Header ──
      let y = MARGIN;

      pdf.setFillColor(24, 24, 27);
      pdf.rect(0, 0, PAGE_W, 52, 'F');

      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(22);
      pdf.setFont('helvetica', 'bold');
      pdf.text('PROPERTY INSPECTION', MARGIN, y + 14);
      pdf.setFontSize(16);
      pdf.text('REPORT', MARGIN, y + 22);

      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      if (data.companyName) {
        pdf.text(data.companyName, MARGIN, y + 32);
      }

      const metaX = PAGE_W - MARGIN;
      pdf.setFontSize(9);
      let metaY = y + 14;
      if (data.inspectionDate) {
        pdf.text(`Date: ${data.inspectionDate}`, metaX, metaY, { align: 'right' });
        metaY += 5;
      }
      if (data.inspectorName) {
        pdf.text(`Inspector: ${data.inspectorName}`, metaX, metaY, { align: 'right' });
        metaY += 5;
      }
      if (data.status) {
        pdf.text(`Status: ${data.status}`, metaX, metaY, { align: 'right' });
      }

      y = 60;

      if (data.propertyAddress) {
        pdf.setTextColor(60, 60, 60);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Property:', MARGIN, y);
        pdf.setFont('helvetica', 'normal');
        pdf.text(data.propertyAddress, MARGIN + 22, y);
        y += 10;
      }

      // Summary box
      pdf.setFillColor(245, 245, 245);
      pdf.roundedRect(MARGIN, y, CONTENT_W, 16, 2, 2, 'F');
      pdf.setFontSize(10);
      pdf.setTextColor(80, 80, 80);
      pdf.setFont('helvetica', 'bold');
      pdf.text('SUMMARY', MARGIN + 4, y + 6);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
      const totalPhotos = data.stepsData.reduce((sum, s) => sum + s.photoUrls.length, 0);
      pdf.text(
        `${INSPECTION_STEPS.length} steps  •  ${completedCount} completed  •  ${skippedCount} skipped  •  ${totalPhotos} photos`,
        MARGIN + 4,
        y + 12
      );
      y += 22;

      // ── Fetch photos and polish notes in parallel ──
      toast.info('Loading photos & polishing notes...');
      const allPhotoUrls = data.stepsData.flatMap((s) => s.photoUrls);
      const photoMap = new Map<string, string | null>();

      const [photoResults, polishedNotesMap] = await Promise.all([
        Promise.all(
          allPhotoUrls.map(async (url) => {
            const b64 = await fetchImageAsBase64(url);
            return { url, b64 };
          })
        ),
        polishNotes(data.stepsData).catch(() => new Map<number, string>()),
      ]);

      for (const r of photoResults) {
        photoMap.set(r.url, r.b64);
      }
      toast.info('Building PDF...');

      // ── Render each step ──
      for (let i = 0; i < INSPECTION_STEPS.length; i++) {
        const step = INSPECTION_STEPS[i];
        const stepData = data.stepsData[i];
        const photos = stepData.photoUrls.map((url) => photoMap.get(url)).filter(Boolean) as string[];
        const hasPhotos = photos.length > 0;

        // Use polished notes if available, fallback to raw
        const displayNotes = polishedNotesMap.get(i) || stepData?.notes || '';

        // Calculate needed height: header(11) + photos rows + notes + spacing
        const photoRows = hasPhotos ? Math.ceil(photos.length / 2) : 0;
        const photoHeight = photoRows * (PHOTO_H + 4);
        const notesLines = displayNotes
          ? pdf.splitTextToSize(displayNotes, CONTENT_W - 4)
          : [];
        const notesHeight = notesLines.length * 4 + (notesLines.length > 0 ? 8 : 0);
        const totalNeeded = 11 + photoHeight + notesHeight + 8;

        y = ensureSpace(pdf, y, Math.min(totalNeeded, MAX_Y - MARGIN), pageCount);

        // Step header bar
        pdf.setFillColor(240, 240, 240);
        pdf.roundedRect(MARGIN, y, CONTENT_W, 8, 1, 1, 'F');
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.setTextColor(40, 40, 40);
        pdf.text(`${i + 1}. ${step.title.toUpperCase()}`, MARGIN + 3, y + 5.5);

        if (stepData?.skipped && !hasPhotos) {
          pdf.setFontSize(8);
          pdf.setTextColor(180, 100, 0);
          pdf.text('SKIPPED', PAGE_W - MARGIN - 3, y + 5.5, { align: 'right' });
        } else if (hasPhotos) {
          pdf.setFontSize(8);
          pdf.setTextColor(100, 100, 100);
          pdf.text(`${photos.length} photo${photos.length !== 1 ? 's' : ''}`, PAGE_W - MARGIN - 3, y + 5.5, { align: 'right' });
        }
        y += 11;

        // Render photos 2 per row
        if (hasPhotos) {
          for (let p = 0; p < photos.length; p += 2) {
            y = ensureSpace(pdf, y, PHOTO_H + 4, pageCount);
            try {
              pdf.addImage(photos[p], 'JPEG', MARGIN, y, PHOTO_W, PHOTO_H);
            } catch {
              pdf.setFillColor(230, 230, 230);
              pdf.rect(MARGIN, y, PHOTO_W, PHOTO_H, 'F');
              pdf.setFontSize(8);
              pdf.setTextColor(150, 150, 150);
              pdf.text('Photo unavailable', MARGIN + PHOTO_W / 2, y + PHOTO_H / 2, { align: 'center' });
            }

            if (p + 1 < photos.length) {
              const x2 = MARGIN + PHOTO_W + 5;
              try {
                pdf.addImage(photos[p + 1], 'JPEG', x2, y, PHOTO_W, PHOTO_H);
              } catch {
                pdf.setFillColor(230, 230, 230);
                pdf.rect(x2, y, PHOTO_W, PHOTO_H, 'F');
                pdf.setFontSize(8);
                pdf.setTextColor(150, 150, 150);
                pdf.text('Photo unavailable', x2 + PHOTO_W / 2, y + PHOTO_H / 2, { align: 'center' });
              }
            }
            y += PHOTO_H + 4;
          }
        }

        // Notes below photos
        if (notesLines.length > 0) {
          y = ensureSpace(pdf, y, 12, pageCount);
          pdf.setFontSize(8);
          pdf.setFont('helvetica', 'bold');
          pdf.setTextColor(100, 100, 100);
          pdf.text('Notes:', MARGIN + 3, y);
          y += 4;
          pdf.setFont('helvetica', 'normal');
          pdf.setTextColor(60, 60, 60);
          pdf.setFontSize(9);
          for (const line of notesLines) {
            y = ensureSpace(pdf, y, 5, pageCount);
            pdf.text(line, MARGIN + 3, y);
            y += 4;
          }
        }

        y += 4;
      }

      // ── Add footers to all pages ──
      const total = pageCount.value;
      for (let p = 1; p <= total; p++) {
        pdf.setPage(p);
        addFooter(pdf, p, total, timestamp);
      }

      const blob = pdf.output('blob');
      toast.success('Inspection report generated!');
      return blob;
    } catch (err: any) {
      console.error('PDF generation error:', err);
      toast.error('Failed to generate report');
      return null;
    } finally {
      setGenerating(false);
    }
  }, []);

  const downloadReport = useCallback(
    async (data: InspectionReportData, filename?: string) => {
      const blob = await generateReport(data);
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename || `inspection-report-${Date.now()}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    },
    [generateReport]
  );

  return { generateReport, downloadReport, generating };
}
