import type { BlueprintOpeningScheduleResult } from "./blueprint-opening-schedules.ts";
type QueryError={message?:string}|null;type QueryResult<T>=PromiseLike<{data:T|null;error:QueryError}>;type DbLike={from:(table:string)=>{upsert:(...args:unknown[])=>unknown}};
export async function persistOpeningScheduleMeasurements(svc:DbLike,tenantId:string,input:{import_session_id:string;source_document_id:string;file_name?:string|null;result:BlueprintOpeningScheduleResult}){
 const paths=input.result.items.map((o,i)=>({tenant_id:tenantId,import_session_id:input.import_session_id,source_document_id:input.source_document_id,deterministic_key:`opening-schedule-v1|p${o.page_number}|${o.kind}|${o.mark??i+1}`,path_type:"blueprint_sheet",file_name:input.file_name??null,document_type:"blueprint_set",provider:"user_uploaded_blueprint",page_number:o.page_number,diagram_label:`${o.kind} schedule`,source_text_excerpt:o.source_text,source_coordinates:o.bbox,confidence:o.confidence}));
 if(!paths.length)return{plan_paths:0,measurements:0};
 const pb=svc.from("blueprint_plan_paths").upsert(paths,{onConflict:"import_session_id,deterministic_key"}) as {select:(c:string)=>QueryResult<Array<{id:string;deterministic_key:string}>>};const{data,error}=await pb.select("id,deterministic_key");if(error)throw new Error(`opening_plan_path_upsert_failed:${error.message??"unknown"}`);const ids=new Map((data??[]).map(r=>[r.deterministic_key,r.id]));
 const rows:any[]=[];input.result.items.forEach((o,i)=>{const k=`opening-schedule-v1|p${o.page_number}|${o.kind}|${o.mark??i+1}`;const common={tenant_id:tenantId,import_session_id:input.import_session_id,source_document_id:input.source_document_id,trade_id:"windows_doors",measurement_group:"wall_openings",confidence:o.confidence,plan_path_id:ids.get(k)??null,page_number:o.page_number,metadata:{...o.metadata,kind:o.kind,mark:o.mark,width_ft:o.width_ft,height_ft:o.height_ft,plan_path_key:k,measurement_source:"explicit_schedule"}};rows.push({...common,measurement_key:"window_door_count",quantity:o.quantity,unit:"count",precision:0,source_value_raw:o.source_text,normalized_value:{kind:o.kind,mark:o.mark,quantity:o.quantity},deterministic_key:`opening-schedule-v1|count|${k}`},{...common,measurement_key:"window_door_area_sqft",quantity:o.area_sqft,unit:"sqft",precision:2,source_value_raw:o.source_text,normalized_value:{kind:o.kind,mark:o.mark,area_sqft:o.area_sqft},deterministic_key:`opening-schedule-v1|area|${k}`},{...common,measurement_key:"window_door_perimeter_lf",quantity:o.perimeter_lf,unit:"lf",precision:2,source_value_raw:o.source_text,normalized_value:{kind:o.kind,mark:o.mark,perimeter_lf:o.perimeter_lf},deterministic_key:`opening-schedule-v1|perimeter|${k}`});});
 const mb=svc.from("blueprint_measurement_objects").upsert(rows,{onConflict:"import_session_id,deterministic_key"}) as {select:(c:string)=>QueryResult<Array<{id:string}>>};const mr=await mb.select("id");if(mr.error)throw new Error(`opening_measurement_upsert_failed:${mr.error.message??"unknown"}`);return{plan_paths:paths.length,measurements:rows.length};
}
