-- 1) Fix referral trigger: jobs.status is enum 'job_status'; lower(text) needs cast
CREATE OR REPLACE FUNCTION public.fn_referral_reward_on_job_status()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_conv RECORD;
  v_code RECORD;
  v_existing uuid;
BEGIN
  IF NEW.status IS NULL THEN
    RETURN NEW;
  END IF;

  IF lower(NEW.status::text) NOT IN ('sold', 'paid', 'completed') THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' AND OLD.status IS NOT DISTINCT FROM NEW.status THEN
    RETURN NEW;
  END IF;

  FOR v_conv IN
    SELECT * FROM public.referral_conversions WHERE job_id = NEW.id
  LOOP
    SELECT id INTO v_existing FROM public.referral_rewards
      WHERE referral_conversion_id = v_conv.id LIMIT 1;
    IF v_existing IS NOT NULL THEN CONTINUE; END IF;

    SELECT * INTO v_code FROM public.referral_codes WHERE id = v_conv.referral_code_id;

    INSERT INTO public.referral_rewards (
      tenant_id, referral_conversion_id, recipient_contact_id,
      reward_type, reward_value, status, notes
    ) VALUES (
      v_conv.tenant_id, v_conv.id, v_conv.referrer_contact_id,
      COALESCE(v_code.reward_type, 'cash'),
      COALESCE(v_code.reward_value, 0),
      'eligible',
      'Auto-created when job status changed to ' || NEW.status::text
    );
  END LOOP;

  RETURN NEW;
END;
$function$;

-- 2) Stage CSV rows
CREATE TEMP TABLE _redline(name text,addr text,qs text,ps text);
INSERT INTO _redline(name,addr,qs,ps) VALUES
  ('paul dondlinger','2760 royal palm dr','interested','lead'),
  ('522 northwest 33rd street','522 northwest 33rd street','interested','lead'),
  ('joanne vincelli','6578 geneva st','qualified','contracted'),
  ('alexa barragan','3985 massini ave','old_roof_marketing','lead'),
  ('oscar olaussen','3397 colma st','old_roof_marketing','lead'),
  ('susan schibinger','7172 nw 62nd ter','old_roof_marketing','lead'),
  ('barbara morrison','6688 nw 62nd ter','old_roof_marketing','lead'),
  ('elysee sinclair','6670 nw 62nd ter','new_roof','lead'),
  ('rodrigo lara','6256 nw 62nd ter','old_roof_marketing','lead'),
  ('6011 northwest 62nd terrace','6011 northwest 62nd terrace','old_roof_marketing','lead'),
  ('lidia zagarolo','5912 nw 62nd ter','old_roof_marketing','lead'),
  ('michael shea','5999 nw 62nd ter','old_roof_marketing','lead'),
  ('jack rutenberg','5847 nw 62nd ter','old_roof_marketing','lead'),
  ('stacy tarakofsky','6093 nw 62nd ter','old_roof_marketing','lead'),
  ('linda king','6258 nw 80th ter','old_roof_marketing','lead'),
  ('joelle guarino','6255 nw 80th ter','old_roof_marketing','lead'),
  ('gabriella alcantara','6326 nw 80th ter','old_roof_marketing','lead'),
  ('brian hall','6359 nw 80th ter','old_roof_marketing','lead'),
  ('max bertrand','6333 nw 80th ter','old_roof_marketing','lead'),
  ('tyrone spong','6466 nw 80th ter','old_roof_marketing','lead'),
  ('nisseth urribarri','5730 nw 77th ter','old_roof_marketing','lead'),
  ('richardo majka','6171 nw 77th ter','old_roof_marketing','lead'),
  ('diane al randolph','6228 nw 77th ter','old_roof_marketing','lead'),
  ('barbara pac','6318 nw 77th ter','old_roof_marketing','lead'),
  ('jean catts','6213 nw 74th ter','old_roof_marketing','lead'),
  ('jerry kranepool','6186 nw 74th ter','old_roof_marketing','lead'),
  ('maria castano perez','6114 nw 74th ter','old_roof_marketing','lead'),
  ('richard gibbs','6044 nw 74th ter','old_roof_marketing','lead'),
  ('federico jen','5978 nw 74th ter','old_roof_marketing','lead'),
  ('milana meshenberg','6237 nw 74th ter','old_roof_marketing','lead'),
  ('kari orfanos','6095 nw 75th way','old_roof_marketing','lead'),
  ('jordan fleisher','5960 nw 75th way','old_roof_marketing','lead'),
  ('abby grubor','6276 nw 75th way','old_roof_marketing','lead'),
  ('ena lucas','4473 nw 67th ave','old_roof_marketing','lead'),
  ('natasha siewrattan','4453 nw 67th ave','old_roof_marketing','lead'),
  ('surjeet kohli','4901 godfrey rd','old_roof_marketing','lead'),
  ('6586 geneva street','6586 geneva street','qualified','contracted'),
  ('javier himelstein','3260 n 46th ave','storm_damage','lead'),
  ('constanza otero','1239 ballard green pl','unqualified','lead'),
  ('samuel cruz','1241 ballard green pl','storm_damage','lead'),
  ('mark sandag','6916 crown lake dr','storm_damage','lead'),
  ('tiara jester','6920 crown lake dr','storm_damage','lead'),
  ('lana berkman','6938 crown lake drive','storm_damage','lead'),
  ('robert beharry','6947 crown lake drive','storm_damage','lead'),
  ('yvette castillo','6913 waterbrook ct','storm_damage','lead'),
  ('jose jimenez','6915 waterbrook ct','storm_damage','lead'),
  ('dalitha gambrell','6914 waterbrook ct','storm_damage','lead'),
  ('rojenet antoine','12705 kings lake dr','storm_damage','lead'),
  ('juan ascencio','12716 kings lake dr','storm_damage','lead'),
  ('julissa solano','12741 kings lake dr','storm_damage','lead'),
  ('john whitaker','12821 kings lake dr','storm_damage','lead'),
  ('gerald bamford','12824 kings lake dr','storm_damage','lead'),
  ('mark gemberling','12830 kings lake dr','storm_damage','lead'),
  ('anthony padron','12840 kings lake dr','storm_damage','lead'),
  ('tonja bracy','13020 waterbourne dr','storm_damage','lead'),
  ('jose dejesus','13031 waterbourne dr','storm_damage','lead'),
  ('dana royce','7408 ridge rd','storm_damage','lead'),
  ('nicholas jodhan','7349 featherstone blvd','storm_damage','lead'),
  ('kevin lu','4961 gardiners bay cir','storm_damage','lead'),
  ('elizabeth batchie','6268 donnington ct','storm_damage','lead'),
  ('katelyn escanillas','6291 sturbridge ct','storm_damage','lead'),
  ('judith bell','6270 sturbridge ct','storm_damage','lead'),
  ('5032 sturbridge court','5032 sturbridge court','storm_damage','lead'),
  ('carmen gomez','6212 weymouth dr','storm_damage','lead'),
  ('alex morgan','6264 weymouth dr','unqualified','lead'),
  ('stacy centeno','6387 sturbridge ct','storm_damage','lead'),
  ('shawn orr','6279 buckingham st','storm_damage','lead'),
  ('noel schultz','4986 oldham st','storm_damage','lead'),
  ('jean thomassy','4974 oldham st','storm_damage','lead'),
  ('4970 oldham street','4970 oldham street','storm_damage','lead'),
  ('maria replane','4942 oldham st','storm_damage','lead'),
  ('alan richardson','6256 weymouth dr','storm_damage','lead'),
  ('shelly maddox','4621 meadowview cir','interested','lead'),
  ('kathryn mary','4617 meadowview cir','interested','lead'),
  ('william bryan','4713 meadowview blvd','interested','lead'),
  ('sarah sloan','4729 meadowview cir','interested','lead'),
  ('4725 meadowview circle','4725 meadowview circle','interested','lead'),
  ('4648 meadowview circle','4648 meadowview circle','interested','lead'),
  ('paul sloan','4623 meadowview cir','storm_damage','lead'),
  ('toni sexton','4615 meadowview cir','interested','lead'),
  ('jason matthews','4603 meadowview cir','storm_damage','lead'),
  ('joseph vollmann','8804 50th ave w','storm_damage','lead'),
  ('carl bell','8708 50th ave w','storm_damage','lead'),
  ('dorothy kelly','8608 50th ave w','storm_damage','lead'),
  ('carolyn dorl','5017 86th street ct w','storm_damage','lead'),
  ('8607 51st avenue west','8607 51st avenue west','storm_damage','lead'),
  ('francesa salamone','8704 51st ave w','storm_damage','lead'),
  ('joseph cordasco','8711 51st ave w','storm_damage','lead'),
  ('dennis nostrand','8703 51st ave w','new_roof','lead'),
  ('millie kempe','8707 51st ave w','storm_damage','lead'),
  ('elwin brady','5212 88th st w','storm_damage','lead'),
  ('charm stenersen','8721 54th ave w','storm_damage','lead'),
  ('walter merkler','6204 trophy ln','storm_damage','lead'),
  ('arne pontan','5410 title row dr','storm_damage','lead'),
  ('theodore fuger','5203 title row dr','storm_damage','lead'),
  ('betsy tavernier','5204 title row dr','storm_damage','lead'),
  ('christine iacovone','5326 title row dr','storm_damage','lead'),
  ('jiri krouzek','5510 inspiration ter','new_roof','lead'),
  ('manju singh','5606 inspiration ter','new_roof','lead'),
  ('howard panes','5610 inspiration ter','new_roof','lead'),
  ('paul parrish','3629 avenida madera','storm_damage','lead'),
  ('3414 avenida madera','3414 avenida madera','storm_damage','lead'),
  ('randy rickman','6237 45th ln e','storm_damage','lead'),
  ('barry hynes','6244 45th ln e','storm_damage','lead'),
  ('rhonda lipp','6238 45th ln e','storm_damage','lead'),
  ('james clarke','4608 62nd ter e','storm_damage','lead'),
  ('4620 62nd terrace east','4620 62nd terrace east','new_roof','lead'),
  ('john hodges','4616 62nd ter e','storm_damage','lead'),
  ('henry blocker','6125 41st st e','storm_damage','lead'),
  ('6098 39th court east','6098 39th court east','storm_damage','lead'),
  ('emily hirshman','6056 39th ct e','storm_damage','lead'),
  ('bettylou heiden','6052 39th ct e','new_roof','lead'),
  ('elimeneth mazzone','6049 39th ct e','storm_damage','lead'),
  ('vincent lijoi','6021 39th ct e','storm_damage','lead'),
  ('brittany farrell','6025 39th ct e','storm_damage','lead'),
  ('daniel mathes','4685 56th dr e','storm_damage','lead'),
  ('patricia helm','4660 56th ter e','storm_damage','lead'),
  ('amanda goff','5924 48th st e','storm_damage','lead'),
  ('amanda hirst','5210 60th dr e','new_roof','lead'),
  ('danielle roman','5206 60th dr e','storm_damage','lead'),
  ('jonathan deveaux','5214 60th dr e','storm_damage','lead'),
  ('phuong nguyen','5218 60th dr e','storm_damage','lead'),
  ('gerald mckinley','5931 53rd ln e','storm_damage','lead'),
  ('melissa morrow','5927 53rd ln e','storm_damage','lead'),
  ('matthew white','5903 53rd ln e','new_roof','lead'),
  ('rene briones','5911 53rd ln e','storm_damage','lead'),
  ('luz hernandez','5907 53rd ln e','storm_damage','lead'),
  ('brian la','5208 58th ter e','new_roof','lead'),
  ('james riley jr','5211 58th ter e','storm_damage','lead'),
  ('rami herbawi','5111 58th ter e','new_roof','lead'),
  ('marguerite raymond','5109 58th ter e','new_roof','lead'),
  ('baltazar vallejo','5107 58th ter e','storm_damage','lead'),
  ('zadiel rodriguez','5006 58th ter e','new_roof','lead'),
  ('thy le','5003 58th ter e','storm_damage','lead'),
  ('diana correa','4609 61st dr e','storm_damage','lead'),
  ('6108 46th street east','6108 46th street east','interested','lead'),
  ('angela roselli','6104 46th st e','storm_damage','lead'),
  ('6112 46th street east','6112 46th street east','storm_damage','lead'),
  ('mitchell delay','6116 46th st e','interested','lead'),
  ('pierre osit','6144 46th st e','storm_damage','lead'),
  ('manisha patel','6130 46th ln e','storm_damage','lead'),
  ('rene rivas','6126 47th st e','storm_damage','lead'),
  ('ibrahim alnadi','6111 47th st e','interested','lead'),
  ('yiu chan','6134 47th st e','new_roof','lead'),
  ('robert palmer','6138 47th st e','interested','lead'),
  ('luis savigne','6146 47th st e','storm_damage','lead'),
  ('michael matzkevich','6142 47th st e','storm_damage','lead'),
  ('rosa medeiros','4615 62nd ave e','storm_damage','lead'),
  ('4635 47th street east','4635 47th street east','storm_damage','lead'),
  ('4620 62nd avenue east','4620 62nd avenue east','storm_damage','lead'),
  ('salem ali','4616 62nd ave e','interested','lead'),
  ('abdulmalik johnson','617 washita stone dr','storm_damage','lead'),
  ('margo phillips','5903 menorca ln','storm_damage','lead'),
  ('derek davis','1337 jumana loop','storm_damage','lead'),
  ('1336 puerto drive','1336 puerto drive','storm_damage','lead'),
  ('fang cheng','6317 marbella blvd','new_roof','lead'),
  ('michael thomas','3518 tangier ter','storm_damage','lead'),
  ('paul adams','3710 tangier ter','new_roof','lead'),
  ('james mucha','3740 tangier ter','new_roof','lead'),
  ('doris swor','3901 red rock way','new_roof','lead'),
  ('barbara brown','3910 red rock way','new_roof','lead'),
  ('christopher knipp','3921 red rock way','new_roof','lead'),
  ('3940 red rock way','3940 red rock way','new_roof','lead'),
  ('jeanette delgado','3953 red rock way','new_roof','lead'),
  ('morgan watkins','1410 quail dr','new_roof','lead'),
  ('schascle yochim','1332 quail dr','new_roof','lead'),
  ('robert geyer','1220 n lake shore dr','storm_damage','lead'),
  ('helen tucker','1580 kenilworth st','storm_damage','lead'),
  ('gail karp','1508 shelburne ln','storm_damage','lead'),
  ('blake mccauley','1724 shelburne ln','storm_damage','lead'),
  ('michael mcdonald','1736 shelburne ln','storm_damage','lead'),
  ('john turgeon','1610 ridgewood ln','storm_damage','lead'),
  ('6414 beechwood avenue','6414 beechwood avenue','storm_damage','lead'),
  ('john cook','6430 beechwood ave','storm_damage','lead'),
  ('jung jones','1023 contento st','new_roof','lead'),
  ('theodore ritter','1031 contento st','new_roof','lead'),
  ('sonya sawers','1038 contento st','new_roof','lead'),
  ('ian myers','1030 contento st','new_roof','lead'),
  ('5539 contento drive','5539 contento drive','storm_damage','lead'),
  ('jody infanger','5607 cape leyte dr','storm_damage','lead'),
  ('gavin bray','1200 s view dr','new_roof','lead'),
  ('mark davis','1249 s view dr','new_roof','lead'),
  ('ileen isaac','5427 siesta cove dr','new_roof','lead'),
  ('maureen maguire','5424 siesta cove dr','new_roof','lead'),
  ('douglas lumpkin','5421 siesta cove dr','new_roof','lead'),
  ('benny varghese','5303 siesta cove dr','new_roof','lead'),
  ('charlotte kovach','5232 siesta cove dr','new_roof','lead'),
  ('wayne ives','5227 siesta cove dr','new_roof','lead'),
  ('oliver hawes','5219 siesta cove dr','new_roof','lead'),
  ('enriqueto rey','5215 siesta cove dr','new_roof','lead'),
  ('nicole roberts','5208 siesta cove dr','new_roof','lead'),
  ('kristin pflugner','5204 siesta cove dr','new_roof','lead'),
  ('robt betette','5200 siesta cove dr','new_roof','lead'),
  ('grace lauderdale','644 tropical cir','new_roof','lead'),
  ('phyllis magnes','622 tropical cir','new_roof','lead'),
  ('635 tropical circle','635 tropical circle','storm_damage','lead'),
  ('sonila cook','786 tropical cir','interested','lead'),
  ('kathleen kuss','768 tropical cir','storm_damage','lead'),
  ('patricia peyser','732 tropical cir','storm_damage','lead'),
  ('marlon wolcott','700 tropical cir','new_roof','lead'),
  ('phillip meyer','690 tropical cir','new_roof','lead'),
  ('jeff wuagneux','1326 roberts bay ln','storm_damage','lead'),
  ('759 birdsong lane','759 birdsong lane','storm_damage','lead'),
  ('sueanne mazzurco','783 birdsong ln','new_roof','lead'),
  ('roseanne tizzano','791 birdsong ln','new_roof','lead'),
  ('john mccarthy','660 venice ln','storm_damage','lead'),
  ('catherine skuba','600 venice ln','new_roof','lead'),
  ('james oriol','5027 commonwealth dr','new_roof','lead'),
  ('john davidson','5030 commonwealth dr','new_roof','lead'),
  ('won huh','5111 dewey pl','interested','lead'),
  ('benjamin nathanson','5112 oakmont pl','new_roof','lead'),
  ('jennifer mooney','5111 oakmont pl','storm_damage','lead'),
  ('thomas mclean','5103 oakmont pl','storm_damage','lead'),
  ('june braccia','5104 oakmont pl','interested','lead'),
  ('5070 commonwealth drive','5070 commonwealth drive','interested','lead'),
  ('courtney bonacuse','5050 commonwealth dr','new_roof','lead'),
  ('dean dubois','5045 commonwealth dr','storm_damage','lead'),
  ('ronni tudin','4938 commonwealth dr','storm_damage','lead'),
  ('melanie sarvis','572 commonwealth ln','storm_damage','lead'),
  ('sarah bueno','617 mangrove point rd','storm_damage','lead'),
  ('john papp','4294 hearthstone dr','storm_damage','lead'),
  ('lewis marian','8867 huntington pointe dr','unqualified','lead'),
  ('madeline bloom','8990 huntington pointe dr','storm_damage','lead'),
  ('shuai shao','682 clear creek dr','unqualified','lead'),
  ('douglas parker','731 fordingbridge way','unqualified','lead'),
  ('matthew konet','735 fordingbridge way','storm_damage','lead'),
  ('jinbo yin','739 fordingbridge way','storm_damage','lead'),
  ('patrick gallahan','1129 scherer way','storm_damage','lead'),
  ('nancy dale','832 golden pond ct','unqualified','lead'),
  ('tonya eubank','901 eagle isle ct','unqualified','lead'),
  ('jessica fernandez','1081 scherer way','storm_damage','lead'),
  ('aurelia hrab','1080 scherer way','storm_damage','lead'),
  ('michael yohn','850 placid lake dr','storm_damage','lead'),
  ('pragya sharma','819 golden pond ct','storm_damage','lead'),
  ('tracey winters','812 golden pond ct','storm_damage','lead'),
  ('deborah petrilli','472 park trace blvd','storm_damage','lead'),
  ('yong liu','818 oak briar ln','storm_damage','lead'),
  ('francis matejik','1712 grande park dr','unqualified','lead'),
  ('willard drake','20 grand palms blvd','unqualified','lead'),
  ('gabriele anderson','74 cayman isles blvd','storm_damage','lead'),
  ('raymond humphrey','24 dominica dr','storm_damage','lead'),
  ('2771 north beach road','2771 north beach road','storm_damage','lead'),
  ('clyde lovelady','1922 mississippi ave','storm_damage','lead'),
  ('john caracciolo','1952 wyoming ave','unqualified','lead'),
  ('glenn fleming','199 boundary blvd','unqualified','lead'),
  ('kevin o connell','173 rotonda cir','unqualified','lead'),
  ('daniel fiore','152 rotonda cir','unqualified','lead'),
  ('joseph domiano','18 annapolis ln','unqualified','lead'),
  ('nicole kramer','64 annapolis ln','unqualified','lead'),
  ('brittany leclerc','85 annapolis ln','unqualified','lead'),
  ('wayne scherrer','100 annapolis ln','unqualified','lead'),
  ('linda szantai','119 annapolis ln','storm_damage','lead'),
  ('santos dos','123 annapolis ln','unqualified','lead'),
  ('douglas jarchow','139 annapolis ln','unqualified','lead'),
  ('patti johnson','148 annapolis ln','unqualified','lead'),
  ('lilli peschke','133 caddy rd','unqualified','lead'),
  ('russell kelahan','107 caddy rd','unqualified','lead'),
  ('james scheuerell','89 caddy rd','unqualified','lead'),
  ('keith keiderling','69 caddy rd','unqualified','lead'),
  ('suzanne edwards','63 caddy rd','unqualified','lead'),
  ('dakota beyer','24 caddy rd','unqualified','lead'),
  ('margaret lyon','4 caddy rd','unqualified','lead'),
  ('carol alexander','1 caddy rd','unqualified','lead'),
  ('jeremy leff','25 oakland hills ct','unqualified','lead'),
  ('patricia bak','23 oakland hills ct','unqualified','lead'),
  ('brenda souza','18 oakland hills ct','unqualified','lead'),
  ('david price','17 oakland hills ct','unqualified','lead'),
  ('ricardo escobedo','11 oakland hills ct','unqualified','lead'),
  ('mark krumenacker','9 oakland hills ct','unqualified','lead'),
  ('linda crombie','6 oakland hills ct','unqualified','lead'),
  ('robin randall','4 oakland hills ct','unqualified','lead'),
  ('teresa new','2 oakland hills ct','unqualified','lead'),
  ('7350 periwinkle drive','7350 periwinkle drive','storm_damage','lead'),
  ('matthew perry','7351 periwinkle dr','storm_damage','lead'),
  ('rebecca felix','1541 caribbean dr','storm_damage','lead'),
  ('anthony kadzius','4528 spring flower ct','storm_damage','lead'),
  ('john bart','4550 spring flower ct','storm_damage','lead'),
  ('thomas roberts','4966 fallcrest cir','unqualified','lead'),
  ('zitomer lyne','6501 mauna loa blvd','storm_damage','lead'),
  ('ernest bowery','2992 seasons blvd','storm_damage','lead'),
  ('brandon kirsten','2952 seasons blvd','storm_damage','lead'),
  ('teresa wor','8247 barton farms blvd','storm_damage','lead'),
  ('dan hicks','8222 barton farms blvd','storm_damage','lead'),
  ('irvin slabach','8255 barton farms blvd','storm_damage','lead'),
  ('james pantos','2885 grazeland dr','storm_damage','lead'),
  ('nancy iaccino','2883 grazeland dr','storm_damage','lead'),
  ('salina mostajabian','2872 grazeland dr','storm_damage','lead'),
  ('michael richland','8242 barton farms blvd','storm_damage','lead'),
  ('charles robbins','2497 farms ct','storm_damage','lead'),
  ('konstantin surkov','8271 barton farms blvd','storm_damage','lead'),
  ('lili nikolova','8256 barton farms blvd','storm_damage','lead'),
  ('kevin ogrady','8262 barton farms blvd','storm_damage','lead'),
  ('lilia pinsky','8274 barton farms blvd','storm_damage','lead'),
  ('renata firlej','8289 barton farms blvd','storm_damage','lead'),
  ('stephanie dulaney','8440 big buck ln','storm_damage','lead'),
  ('annette fraczak','8290 roseburn ct','storm_damage','lead'),
  ('robert mazurek','8284 roseburn ct','storm_damage','lead'),
  ('nunzio olivieri','3979 founders club dr','storm_damage','lead'),
  ('stephanie lewin','3591 founders club dr','storm_damage','lead'),
  ('miguel acosta','9242 mcdaniel ln','storm_damage','lead'),
  ('james agee','5786 inkberry cir','interested','lead'),
  ('michael lowe','9666 82nd ave','storm_damage','lead'),
  ('gerald rosplock','6829 country lakes cir','interested','lead'),
  ('richard pfenninger','6816 country lakes cir','storm_damage','lead'),
  ('norma irvin','7921 broadmoor pines blvd','storm_damage','lead'),
  ('ruth ratliff','7908 broadmoor pines blvd','unqualified','lead'),
  ('calvin nissley','5960 country club way','storm_damage','lead'),
  ('robert sollenberger','7421 fairlinks ct','storm_damage','lead'),
  ('kimberly arnold','7419 fairlinks ct','storm_damage','lead'),
  ('michael toland','5815 fairwoods cir','storm_damage','lead'),
  ('annastacia benzing','5817 fairwoods cir','storm_damage','lead'),
  ('tom marsh','363 yacht harbor dr','storm_damage','lead'),
  ('john richard','500 yacht harbor dr','storm_damage','lead'),
  ('jeanne mccue','1236 yacht harbor dr','storm_damage','lead'),
  ('stephen druhe','106 dory ln','storm_damage','lead'),
  ('kathleen keith','1375 windward dr','storm_damage','lead'),
  ('daniel kriwitsky','105 yacht harbor dr','storm_damage','lead'),
  ('pete sanidas','1484 seafarer dr','storm_damage','lead'),
  ('barbara sylvester','2880 casey key rd','storm_damage','lead'),
  ('jeffrey brandon','2890 casey key rd','storm_damage','lead'),
  ('judith oates','2823 casey key rd','storm_damage','lead'),
  ('oscar estrada','2557 casey key rd','storm_damage','lead'),
  ('1822 casey key road','1822 casey key road','storm_damage','lead'),
  ('jason lee','1704 casey key rd','storm_damage','lead'),
  ('thomas southwell','13350 verandi st','storm_damage','lead'),
  ('buddy hill','13428 verandi street','interested','lead'),
  ('13434 verandi street','13434 verandi street','storm_damage','lead'),
  ('4264 cuthbert ave','4264 cuthbert ave','old_roof_marketing','lead'),
  ('4245 mocha ave','4245 mocha ave','storm_damage','lead'),
  ('549 spinnaker dr','549 spinnaker dr','storm_damage','lead'),
  ('deborah widmeier','595 tigertail ct','old_roof_marketing','lead'),
  ('2961 tuckerstown dr','2961 tuckerstown dr','old_roof_marketing','lead'),
  ('frances scully','2848 coventry dr','old_roof_marketing','lead'),
  ('katherine bonnici','2819 coventry dr','old_roof_marketing','lead'),
  ('elizabeth cruz','2733 coventry dr','old_roof_marketing','lead'),
  ('lucille watson','2727 coventry dr','old_roof_marketing','lead'),
  ('melissa deitsch','3936 torrey pines blvd','old_roof_marketing','lead'),
  ('janice abele','3932 torrey pines blvd','old_roof_marketing','lead'),
  ('valerie goldstein','3776 prairie dunes dr','old_roof_marketing','lead'),
  ('3800 prairie dunes drive','3800 prairie dunes drive','old_roof_marketing','lead'),
  ('marcia rickenbacker','3846 spyglass hill rd','old_roof_marketing','lead'),
  ('3750 spyglass hill road','3750 spyglass hill road','storm_damage','lead'),
  ('3737 spyglass hill road','3737 spyglass hill road','old_roof_marketing','lead'),
  ('3711 spyglass hill road','3711 spyglass hill road','old_roof_marketing','lead'),
  ('3761 spyglass hill road','3761 spyglass hill road','old_roof_marketing','lead'),
  ('james haggard','3930 spyglass hill rd','old_roof_marketing','lead'),
  ('marina paraboschi','3936 spyglass hill rd','old_roof_marketing','lead'),
  ('3972 spyglass hill road','3972 spyglass hill road','old_roof_marketing','lead'),
  ('michael stokes','3951 torrey pines blvd','old_roof_marketing','lead'),
  ('dwight hunter','3943 torrey pines blvd','old_roof_marketing','lead'),
  ('3927 torrey pines boulevard','3927 torrey pines boulevard','old_roof_marketing','lead'),
  ('darla o brien','3870 torrey pines blvd','old_roof_marketing','lead'),
  ('wayne muck','3861 torrey pines blvd','old_roof_marketing','lead'),
  ('john barbagallo','3819 torrey pines blvd','old_roof_marketing','lead'),
  ('janet sieve','3776 torrey pines blvd','old_roof_marketing','lead'),
  ('steven titunik','3769 torrey pines blvd','old_roof_marketing','lead'),
  ('martha van winkle','6435 woodbirch pl','old_roof_marketing','lead'),
  ('devin radkay','6466 woodbirch pl','old_roof_marketing','lead'),
  ('kathleen rutledge','1815 n lake shore dr','old_roof_marketing','lead'),
  ('kevin butt','1603 kenilworth st','old_roof_marketing','lead'),
  ('steven sauers','1647 arlington st','old_roof_marketing','lead'),
  ('zoya kosman','1704 floyd st','old_roof_marketing','lead'),
  ('john ledyard','1929 innisbrook ct','old_roof_marketing','lead'),
  ('michael schwegel','1920 innisbrook ct','storm_damage','lead'),
  ('david williams','1918 innisbrook ct','old_roof_marketing','lead'),
  ('kenneth ormerod','904 pinehurst ln','old_roof_marketing','lead'),
  ('susan jansen','979 n doral ln','old_roof_marketing','lead'),
  ('peter ambery','987 n doral ln','old_roof_marketing','lead'),
  ('jacquelyn o brien','909 s doral ln','old_roof_marketing','lead'),
  ('elizabeth prince','924 s doral ln','old_roof_marketing','lead'),
  ('james baker','938 s doral ln','old_roof_marketing','lead'),
  ('angelina tarolli','941 s doral ln','old_roof_marketing','lead'),
  ('paul alkema','958 n doral ln','old_roof_marketing','lead'),
  ('316 langholm dr','316 langholm dr','old_roof_marketing','lead'),
  ('mary stack','318 langholm dr','old_roof_marketing','lead'),
  ('kevin militello','173 braemar ave','old_roof_marketing','lead'),
  ('lilia pokrovsky','180 braemar ave','old_roof_marketing','lead'),
  ('mary moyer','225 wetherby st','old_roof_marketing','lead'),
  ('burton gerber','224 wetherby st','old_roof_marketing','lead'),
  ('228 wetherby street','228 wetherby street','old_roof_marketing','lead'),
  ('rober prince','232 wetherby st','old_roof_marketing','lead'),
  ('charla newland','216 wetherby st','old_roof_marketing','lead'),
  ('prasan connor','1562 landings ter','new_roof','lead'),
  ('marc grinberg','1598 landings ter','old_roof_marketing','lead'),
  ('evan danzig','1592 landings ter','old_roof_marketing','lead'),
  ('kathleen marques','1669 landings ln','old_roof_marketing','lead'),
  ('patrick benz','1681 landings ln','old_roof_marketing','lead'),
  ('james woods','1675 landings ln','storm_damage','lead'),
  ('kimberli harris','1663 landings ln','new_roof','lead'),
  ('blake quigley','1699 landings ln','new_roof','lead'),
  ('james stewart','1700 landings blvd','new_roof','lead'),
  ('eileen schineller','1712 landings blvd','new_roof','lead'),
  ('ilona kuchta','1724 landings blvd','new_roof','lead'),
  ('katherine hansen','1729 landings way','new_roof','lead'),
  ('kim wheeler','1735 landings way','old_roof_marketing','lead'),
  ('guy bernheim','1741 landings way','new_roof','lead'),
  ('arlene sperhac','5038 kestral park way s','old_roof_marketing','lead'),
  ('5050 kestral park way s','5050 kestral park way s','new_roof','lead'),
  ('thomas pennie','5062 kestral park way s','new_roof','lead'),
  ('donna bewley','5086 kestral park','old_roof_marketing','lead'),
  ('patricia shrope','5160 kestral park ter','old_roof_marketing','lead'),
  ('5158 kestral park terrace','5158 kestral park terrace','storm_damage','lead'),
  ('5133 kestral park place','5133 kestral park place','old_roof_marketing','lead'),
  ('5122 kestral park way south','5122 kestral park way south','old_roof_marketing','lead'),
  ('elida ramberger','5121 kestral park pl','new_roof','lead'),
  ('robert routh','5129 kestral park pl','new_roof','lead'),
  ('brian baldwin','5127 kestral park pl','new_roof','lead'),
  ('veronica day','5125 kestral park pl','new_roof','lead'),
  ('ira klein','5123 kestral park pl','old_roof_marketing','lead'),
  ('lisa fluharty','5119 kestral park pl','new_roof','lead'),
  ('jill gates','5110 kestral park way s','old_roof_marketing','lead'),
  ('bruce staniforth','5098 kestral park way s','old_roof_marketing','lead'),
  ('patricia plass','5197 flicker field cir','new_roof','lead'),
  ('gerald padfield','5112 flicker field cir','new_roof','lead'),
  ('julie schoenthaler','5104 flicker field cir','new_roof','lead'),
  ('antoine naaman','5115 flicker field cir','old_roof_marketing','lead'),
  ('ashley sherman','5125 flicker field cir','old_roof_marketing','lead'),
  ('mary kenzie','5120 flicker field cir','new_roof','lead'),
  ('119071fs confidential','5147 flicker field cir','new_roof','lead'),
  ('monte decarlo','5149 flicker field cir','new_roof','lead'),
  ('stephen poyta','5152 flicker field cir','new_roof','lead'),
  ('p solomon','5161 flicker field cir','new_roof','lead'),
  ('bradley springstead','5164 flicker field cir','old_roof_marketing','lead'),
  ('silke cuff','1432 cedar bay ln','new_roof','lead'),
  ('elizabeth kueppers','1435 cedar bay ln','new_roof','lead'),
  ('dagmar ladle','1427 cedar bay ln','new_roof','lead'),
  ('1413 cedar bay lane','1413 cedar bay lane','storm_damage','lead'),
  ('maura semmes','1403 cedar bay ln','new_roof','lead'),
  ('rick kellam','142 rimini way','old_roof_marketing','lead'),
  ('gail lawrence','146 rimini way','old_roof_marketing','lead'),
  ('kyla buckley','150 rimini way','old_roof_marketing','lead'),
  ('kyle maurathpetras','154 rimini way','old_roof_marketing','lead'),
  ('janice brann','154 montelluna dr','old_roof_marketing','lead'),
  ('robert marshhill','158 montelluna dr','old_roof_marketing','lead'),
  ('william jr','162 montelluna dr','old_roof_marketing','lead'),
  ('yan kisen','178 montelluna dr','old_roof_marketing','lead'),
  ('william blomquist','182 montelluna dr','old_roof_marketing','lead'),
  ('vickie gilliland','186 montelluna dr','old_roof_marketing','lead'),
  ('190 montelluna drive','190 montelluna drive','old_roof_marketing','lead'),
  ('kenneth iwanusa','194 montelluna dr','old_roof_marketing','lead'),
  ('john fanelli','198 montelluna dr','old_roof_marketing','lead'),
  ('bonnie tokarz','202 montelluna dr','old_roof_marketing','lead'),
  ('cynthia freeman','206 montelluna dr','old_roof_marketing','lead'),
  ('douglas schwartz','210 montelluna dr','old_roof_marketing','lead'),
  ('steven cerny','214 montelluna dr','old_roof_marketing','lead'),
  ('paul schnackenberg','222 montelluna dr','old_roof_marketing','lead'),
  ('robin yurk','226 montelluna dr','old_roof_marketing','lead'),
  ('albert buholzer','230 montelluna dr','old_roof_marketing','lead'),
  ('8974 grey oaks ave','8974 grey oaks ave','old_roof_marketing','lead'),
  ('douglas conley','9441 cedar ridge ln','old_roof_marketing','lead'),
  ('9552 hawksmoor lane','9552 hawksmoor lane','old_roof_marketing','lead'),
  ('alstair cole','9496 hawksmoor ln','old_roof_marketing','lead'),
  ('9454 hawksmoor lane','9454 hawksmoor lane','old_roof_marketing','lead'),
  ('donald bates','9422 hawksmoor ln','old_roof_marketing','lead'),
  ('john henne','9414 hawksmoor ln','old_roof_marketing','lead'),
  ('marilyn goldfarb','4304 balmoral way','old_roof_marketing','lead'),
  ('lesley patricia','4039 westbourne cir','old_roof_marketing','lead'),
  ('abigail stone','4075 westbourne cir','old_roof_marketing','lead'),
  ('robert kast','4139 westbourne cir','old_roof_marketing','lead'),
  ('richard weissfeld','4014 westbourne cir','old_roof_marketing','lead'),
  ('4173 westbourne circle','4173 westbourne circle','old_roof_marketing','lead'),
  ('4177 westbourne circle','4177 westbourne circle','old_roof_marketing','lead'),
  ('karen wurst','4181 westbourne cir','old_roof_marketing','lead'),
  ('paulette borges','4185 westbourne cir','old_roof_marketing','lead'),
  ('4189 westbourne circle','4189 westbourne circle','old_roof_marketing','lead'),
  ('stanley lusnia','4197 westbourne cir','old_roof_marketing','lead'),
  ('ann marszalek','9008 willow brook dr','storm_damage','lead'),
  ('9120 willow brook dr','9120 willow brook dr','storm_damage','lead'),
  ('carolyn meadowcroft','9113 willow brook dr','storm_damage','lead'),
  ('richard leuner','9096 willow brook dr','old_roof_marketing','lead'),
  ('cheryl wolfe','4156 brookpointe ct','old_roof_marketing','lead'),
  ('vincent ellis','4180 brookpointe ct','storm_damage','lead'),
  ('giuseppe giannini','4188 brookpointe ct','old_roof_marketing','lead'),
  ('ryan shaeffer','1574 peregrine point dr','old_roof_marketing','lead'),
  ('michael furen','1605 peregrine point ct','old_roof_marketing','lead'),
  ('barbara bonina','1718 peregrine point dr','old_roof_marketing','lead'),
  ('1742 peregrine point drive','1742 peregrine point drive','old_roof_marketing','lead'),
  ('sandra masters','1766 peregrine point dr','old_roof_marketing','lead'),
  ('erica friedman','4785 pine harrier dr','old_roof_marketing','lead'),
  ('4773 pine harrier drive','4773 pine harrier drive','old_roof_marketing','lead'),
  ('4737 pine harrier drive','4737 pine harrier drive','old_roof_marketing','lead'),
  ('howard swartz','4653 pine harrier dr','old_roof_marketing','lead'),
  ('richard snyder','4612 pine harrier dr','old_roof_marketing','lead'),
  ('kurstan fox','1672 pine harrier cir','old_roof_marketing','lead'),
  ('masako carlson','1684 pine harrier cir','old_roof_marketing','lead'),
  ('brett johnson','1744 pine harrier cir','old_roof_marketing','lead'),
  ('erin michalopoulos','4824 peregrine point cir w','old_roof_marketing','lead'),
  ('maryanne olmsted','4841 peregrine point cir n','old_roof_marketing','lead'),
  ('dylan mccarthy','4888 peregrine point cir n','old_roof_marketing','lead'),
  ('martin mcgrath','4868 peregrine point cir n','old_roof_marketing','lead'),
  ('david glassman','4856 peregrine point cir n','old_roof_marketing','lead'),
  ('silke thompson','4852 peregrine point cir n','old_roof_marketing','lead'),
  ('alexander david','4840 peregrine point cir n','old_roof_marketing','lead'),
  ('kraig koach','4804 peregrine point cir w','old_roof_marketing','lead'),
  ('nancy blackburn','1527 peregrine point dr','old_roof_marketing','lead'),
  ('5168 kestral park ter','5168 kestral park ter','old_roof_marketing','lead'),
  ('5161 kestral park lane','5161 kestral park lane','old_roof_marketing','lead'),
  ('john alogna','5155 kestral park ln','old_roof_marketing','lead'),
  ('5155 flicker field circle','5155 flicker field circle','old_roof_marketing','lead'),
  ('106 savona way','106 savona way','storm_damage','lead'),
  ('larry konkel','122 savona way','storm_damage','lead'),
  ('james blackburn','282 montelluna dr','storm_damage','lead'),
  ('sally effron','293 mestre pl','storm_damage','lead'),
  ('paul helmkamp','306 mestre pl','storm_damage','lead'),
  ('david macpherson','234 mestre pl','storm_damage','lead'),
  ('paul cornwell','501 montelluna dr','old_roof_marketing','lead'),
  ('chad cloninger','506 montelluna dr','old_roof_marketing','lead'),
  ('joseph michaels','502 montelluna dr','old_roof_marketing','lead'),
  ('conrad zvara','498 montelluna dr','old_roof_marketing','lead'),
  ('alexsandra fridshtand','434 montelluna dr','old_roof_marketing','lead'),
  ('barry westergreen','421 montelluna dr','old_roof_marketing','lead'),
  ('walter sanders','405 montelluna dr','storm_damage','lead'),
  ('william tvenstrup','410 montelluna dr','storm_damage','lead'),
  ('paul renkens','406 montelluna dr','old_roof_marketing','lead'),
  ('fatima rojas gonzalez','353 montelluna dr','new_roof','lead'),
  ('robert zarella','401 montelluna dr','new_roof','lead'),
  ('317 montelluna drive','317 montelluna drive','storm_damage','lead'),
  ('william midian','321 montelluna dr','old_roof_marketing','lead'),
  ('daniel hoffman','334 montelluna dr','old_roof_marketing','lead'),
  ('bari reitzel','345 montelluna dr','old_roof_marketing','lead'),
  ('anna nesanelis','4969 gardiners bay cir','storm_damage','lead'),
  ('farkhondeh nejad','5564 new covington dr','storm_damage','lead'),
  ('jordan churchill','5568 new covington dr','storm_damage','lead'),
  ('adam wisniowski','5628 new covington dr','old_roof_marketing','lead'),
  ('nicholas ayers','5441 new covington dr','storm_damage','lead'),
  ('stewart jones','5464 new covington dr','storm_damage','lead'),
  ('7604 weeping willow circle','7604 weeping willow circle','old_roof_marketing','lead'),
  ('peter kulla','7316 wax myrtle way','old_roof_marketing','lead'),
  ('gary phillips','913 symphony beach ln','storm_damage','lead'),
  ('tabetha pittman','4597 sunburst ave','qualified','contingency_signed'),
  ('ian nokes','146 savona way','storm_damage','lead'),
  ('daniel lease','269 pesaro dr','storm_damage','lead'),
  ('109 torcello court','109 torcello court','old_roof_marketing','lead'),
  ('maria gerber','113 torcello ct','storm_damage','lead'),
  ('james hardigan','110 torcello ct','new_roof','lead'),
  ('susan spinucci','106 torcello ct','old_roof_marketing','lead'),
  ('geoffrey gardner','138 portofino dr','old_roof_marketing','lead'),
  ('julie kelly','142 portofino dr','new_roof','lead'),
  ('jonathan ratner','141 portofino dr','new_roof','lead'),
  ('guenther grunau','146 portofino dr','old_roof_marketing','lead'),
  ('joanne browning','145 portofino dr','storm_damage','lead'),
  ('bryan challener','149 portofino dr','old_roof_marketing','lead'),
  ('brandi ball','237 portofino dr','old_roof_marketing','lead'),
  ('giorgio sega','233 portofino dr','old_roof_marketing','lead'),
  ('megan nisberg','206 portofino dr','storm_damage','lead'),
  ('shannon treadway','177 portofino dr','storm_damage','lead'),
  ('gregory gardner','202 vicenza way','old_roof_marketing','lead'),
  ('scott lampert','274 pesaro dr','old_roof_marketing','lead'),
  ('josh rojas','262 pesaro dr','storm_damage','lead'),
  ('whitney dupree','290 nw clubview cir','old_roof_marketing','lead'),
  ('todd manning','521 nw clubview cir','old_roof_marketing','lead'),
  ('balubhai patel','726 nw clubview cir','new_roof','lead'),
  ('jayeeni patel','746 nw clubview cir','old_roof_marketing','lead'),
  ('william roddy','755 nw clubview cir','old_roof_marketing','lead'),
  ('nick patel','442 nw fairway dr','qualified','contracted'),
  ('116 nw egret ln','116 nw egret ln','old_roof_marketing','lead'),
  ('vinod patel','238 nw harris lake dr','old_roof_marketing','lead'),
  ('mae sepulveda','208 nw harris lake dr','old_roof_marketing','lead'),
  ('109 northwest harris lake drive','109 northwest harris lake drive','old_roof_marketing','lead'),
  ('stephen smith','102 nw harris lake dr','old_roof_marketing','lead'),
  ('richard rocco','499 nw harris lake dr','interested','lead'),
  ('charles brim','719 nw harris lake dr','storm_damage','lead'),
  ('brenda jones','760 nw harris lake dr','new_roof','lead'),
  ('james meloy','798 nw harris lake dr','new_roof','lead'),
  ('sandra jackson','354 nw harris loop','new_roof','lead'),
  ('reginald taylor','384 nw harris loop','new_roof','lead'),
  ('linda odom','379 nw harris loop','new_roof','lead'),
  ('axel naveira','349 nw harris loop','new_roof','lead'),
  ('zachary bondi','327 nw harris loop','new_roof','lead'),
  ('bonita taylor','326 nw harris loop','new_roof','lead'),
  ('mohammadfoad molamahmoudi','298 nw harris loop','storm_damage','lead'),
  ('sherilyn roberts','247 nw harris loop','old_roof_marketing','lead'),
  ('615 northwest harris lake drive','615 northwest harris lake drive','old_roof_marketing','lead'),
  ('charlotte trowell','559 nw harris lake dr','old_roof_marketing','lead'),
  ('william payne','428 nw harris lake dr','interested','lead'),
  ('angela martin','627 4th st','new_roof','lead'),
  ('bella zarubinsky','6727 41st street cir e','interested','lead'),
  ('vitas mudinas','1145 sw 5th st','new_roof','lead'),
  ('wesley brown','1110 sw 4th st','unqualified','lead'),
  ('john miller','660 sw 17th st','unqualified','lost'),
  ('george najmy','7771 camden harbour drive','unqualified','lead'),
  ('4639 anaconda drive','4639 anaconda drive','interested','lead'),
  ('fred butler','4824 sandpointe dr','interested','lead'),
  ('129 akron road','129 akron road','old_roof_marketing','lead'),
  ('jeffrey druek','2343 ne 29th st','old_roof_marketing','lead'),
  ('aimee lanzaro','3500 ne 23rd ave','old_roof_marketing','lead'),
  ('francis sherman','2411 ne 26th st','old_roof_marketing','lead'),
  ('thomas grant','2249 ne 26th st','old_roof_marketing','lead'),
  ('eileen lamarca','2605 ne 24th st','old_roof_marketing','lead'),
  ('2417 ne 26th ave','2417 ne 26th ave','old_roof_marketing','lead'),
  ('stephen troese','2433 ne 26th ave','old_roof_marketing','lead'),
  ('richard svopa','2449 ne 26th ave','old_roof_marketing','lead'),
  ('john durante','2421 ne 27th st','old_roof_marketing','lead'),
  ('joanne gartenhaus','2346 ne 27th st','old_roof_marketing','lead'),
  ('victoria schwartz','2717 ne 23rd ave','old_roof_marketing','lead'),
  ('lawrence rosen','2398 ne 28th st','old_roof_marketing','lead'),
  ('jeffrey rubin','2385 ne 28th st','old_roof_marketing','lead'),
  ('dee luceri','2366 ne 28th st','old_roof_marketing','lead'),
  ('marion wollum','2333 ne 28th ct','old_roof_marketing','lead'),
  ('2120 northeast 30th street','2120 northeast 30th street','old_roof_marketing','lead'),
  ('2110 northeast 30th street','2110 northeast 30th street','old_roof_marketing','lead'),
  ('marjorie evans','2150 ne 30th st','old_roof_marketing','lead'),
  ('tiffany salas','2260 ne 30th st','old_roof_marketing','lead'),
  ('yolanda giha','2325 ne 30th ct','new_roof','lead'),
  ('ken steigelman','2317 ne 30th ct','new_roof','lead'),
  ('3050 ne 23rd ave','3050 ne 23rd ave','new_roof','lead'),
  ('keith vollberg','1001 nandina dr','new_roof','lead'),
  ('adolfo torres','1650 lone pine way','interested','lead'),
  ('inez silverstein','7203 arcadia bay ct','old_roof_marketing','lead'),
  ('alison rampersad','14576 country side ln','old_roof_marketing','lead'),
  ('david rosov','11434 mauna kea ln','old_roof_marketing','lead'),
  ('joel pearlberg','5723 waterford','old_roof_marketing','lead'),
  ('rr integration test','1102 louisiana ave','interested','lead'),
  ('3919 hidden glen dr','3919 hidden glen dr','old_roof_marketing','lead'),
  ('linda shepard','3910 hidden glen dr','old_roof_marketing','lead'),
  ('marie augustin','3915 hidden glen dr','storm_damage','lead'),
  ('coleen singer','865 elm ct','old_roof_marketing','lead'),
  ('rosa culhane','1337 n collier blvd','old_roof_marketing','lead'),
  ('robert kennedy','475 n collier blvd','old_roof_marketing','lead'),
  ('740 milan ct','740 milan ct','storm_damage','lead'),
  ('james rhodes','741 hernando dr','old_roof_marketing','lead'),
  ('738 hernando drive','738 hernando drive','old_roof_marketing','lead'),
  ('roger sherwin','690 hernando dr','old_roof_marketing','lead'),
  ('691 hernando dr','691 hernando dr','storm_damage','lead'),
  ('georgia christoforou','685 hernando dr','old_roof_marketing','lead'),
  ('680 hernando drive','680 hernando drive','old_roof_marketing','lead'),
  ('william martin','664 hernando dr','old_roof_marketing','lead'),
  ('650 hernando drive','650 hernando drive','old_roof_marketing','lead'),
  ('604 hernando drive','604 hernando drive','old_roof_marketing','lead'),
  ('cathleen gresh','621 kendall dr','old_roof_marketing','lead'),
  ('466 clifton court','466 clifton court','old_roof_marketing','lead'),
  ('karen cichon','478 clifton ct','old_roof_marketing','lead'),
  ('mary teets','483 clifton ct','old_roof_marketing','lead'),
  ('sylvia franks','475 clifton ct','old_roof_marketing','lead'),
  ('colin roberts','630 kendall dr','old_roof_marketing','lead'),
  ('natalja zarembo','356 nw emilia way','unqualified','lead'),
  ('yolanda adams','7778 lake andrea cir','qualified','contingency_signed'),
  ('barbara light','7772 lake andrea cir','interested','lead'),
  ('william tschida','7766 lake andrea cir','qualified','contingency_signed'),
  ('rr integration','1603 ruby st ne','qualified','contracted'),
  ('cherlyn simms','4075 simkins ave','qualified','contracted'),
  ('sainy taha','1681 5th st','interested','lead'),
  ('walter winkler','4397 reflections pkwy','storm_damage','lead'),
  ('irina gorovits','4345 reflections pkwy','storm_damage','lead'),
  ('michael pohl','4310 reflections pkwy','storm_damage','lead'),
  ('charles griffin','4175 reflections pkwy','storm_damage','lead'),
  ('patricia stevenson','4349 reflections pkwy','interested','lead'),
  ('rodney woods','5137 cantabria crst','interested','lead'),
  ('3725 spyglass hill road','3725 spyglass hill road','old_roof_marketing','lead'),
  ('donna murphy','3965 spyglass hill rd','old_roof_marketing','lead'),
  ('3964 torrey pines boulevard','3964 torrey pines boulevard','old_roof_marketing','lead'),
  ('adam rowe','1804 kenilworth st','storm_damage','lead'),
  ('harry carol','153 montelluna dr','old_roof_marketing','lead'),
  ('mary hall','209 montelluna dr','old_roof_marketing','lead'),
  ('thomas dulski','217 montelluna dr','old_roof_marketing','lead'),
  ('denise stormacq','9403 glen abbey ln','storm_damage','lead'),
  ('lois vrable','9456 cedar ridge ln','old_roof_marketing','lead'),
  ('keith messingschlager','9452 cedar ridge ln','old_roof_marketing','lead'),
  ('lyndsay holcomb','4026 westbourne cir','old_roof_marketing','lead'),
  ('catherine lasher','4038 westbourne cir','old_roof_marketing','lead'),
  ('ron tucker','4070 westbourne cir','old_roof_marketing','lead'),
  ('karen cavallo','4082 westbourne cir','old_roof_marketing','lead'),
  ('william scott','4094 westbourne cir','old_roof_marketing','lead'),
  ('ruth meyfarth','4150 westbourne cir','old_roof_marketing','lead'),
  ('charles offer','4182 westbourne cir','old_roof_marketing','lead'),
  ('john schneider','5888 tidewood ave','old_roof_marketing','lead'),
  ('4678 pine harrier drive','4678 pine harrier drive','old_roof_marketing','lead'),
  ('lorenzo berrios','4660 pine harrier dr','old_roof_marketing','lead'),
  ('4638 pine harrier drive','4638 pine harrier drive','old_roof_marketing','lead'),
  ('grace hutchens','1600 pine harrier cir','old_roof_marketing','lead'),
  ('vladislav yeliseyev','4600 pine harrier dr','old_roof_marketing','lead'),
  ('kim salvatori','4615 pine harrier dr','old_roof_marketing','lead'),
  ('tracy mccormick','4627 pine harrier dr','old_roof_marketing','lead'),
  ('1733 pine harrier circle','1733 pine harrier circle','old_roof_marketing','lead'),
  ('leila frangie','1769 pine harrier cir','old_roof_marketing','lead'),
  ('laura cohn','4849 peregrine point cir n','old_roof_marketing','lead'),
  ('robert vermut','4807 peregrine point cir w','old_roof_marketing','lead'),
  ('delisle','4801 peregrine point circle west','old_roof_marketing','lead'),
  ('leslie gray','1419 peregrine point dr','old_roof_marketing','lead'),
  ('joseph padgett','1400 peregrine point dr','old_roof_marketing','lead'),
  ('chase griffin','4955 landings ct','old_roof_marketing','lead'),
  ('robert silverman','5162 kestral park ter','old_roof_marketing','lead'),
  ('irwin starr','5164 kestral park ter','old_roof_marketing','lead'),
  ('dina silverman','5107 flicker field cir','old_roof_marketing','lead'),
  ('constance sergent','5119 flicker field cir','old_roof_marketing','lead'),
  ('emily morgan','5131 flicker field cir','old_roof_marketing','lead'),
  ('bud hurter','5137 flicker field cir','old_roof_marketing','lead'),
  ('igor mihailov','5143 flicker field cir','old_roof_marketing','lead'),
  ('henry germann','309 montelluna dr','qualified','contracted'),
  ('213 martellago dr','213 martellago dr','storm_damage','lead'),
  ('ziad ghamra','1804 morris st','storm_damage','lead'),
  ('elizabeth gibsonwakeman','1908 s orange ave','storm_damage','lead'),
  ('suzanne formento','4990 gardiners bay cir','storm_damage','lead'),
  ('desmond oduffy','4913 bridgehampton blvd','storm_damage','lead'),
  ('lynn millikin','4512 tuscana dr','storm_damage','lead'),
  ('jonathan mosher','4515 tuscana dr','storm_damage','lead'),
  ('elena wallerrybak','1004 piano ln','storm_damage','lead'),
  ('richard rayment','1005 piano ln','storm_damage','lead'),
  ('jean scott','6941 antigua pl','old_roof_marketing','lead'),
  ('elizabeth harlach','3136 lockwood ter','old_roof_marketing','lead'),
  ('kerri gagne','3130 lockwood ter','old_roof_marketing','lead'),
  ('james rennie','3105 gulf gate dr','old_roof_marketing','lead'),
  ('sharon cropper','7109 curtiss ave','storm_damage','lead'),
  ('barbara crane','6506 42nd st e','storm_damage','lead'),
  ('lucy desloge','5185 flicker field cir','interested','lead'),
  ('rr integration test','224 n highland st','interested','lead'),
  ('jeffrey pierson','2200 sandlewood dr','storm_damage','lead');

-- 3) Sync contacts.qualification_status and pipeline_entries.status by normalized name + address
WITH matches AS (
  SELECT c.id AS contact_id, r.qs, r.ps
  FROM contacts c
  JOIN _redline r
    ON regexp_replace(lower(trim(coalesce(c.first_name,'')||' '||coalesce(c.last_name,''))),'[^a-z0-9 ]','','g') = r.name
   AND regexp_replace(lower(trim(coalesce(c.address_street,''))),'[^a-z0-9 ]','','g') = r.addr
)
UPDATE contacts c
   SET qualification_status = m.qs,
       updated_at = now()
  FROM matches m
 WHERE c.id = m.contact_id
   AND (c.qualification_status IS DISTINCT FROM m.qs);

WITH matches AS (
  SELECT pe.id AS pe_id, r.ps
  FROM pipeline_entries pe
  JOIN contacts c ON c.id = pe.contact_id
  JOIN _redline r
    ON regexp_replace(lower(trim(coalesce(c.first_name,'')||' '||coalesce(c.last_name,''))),'[^a-z0-9 ]','','g') = r.name
   AND regexp_replace(lower(trim(coalesce(c.address_street,''))),'[^a-z0-9 ]','','g') = r.addr
  WHERE pe.deleted_at IS NULL
)
UPDATE pipeline_entries pe
   SET status = m.ps,
       updated_at = now()
  FROM matches m
 WHERE pe.id = m.pe_id
   AND (pe.status IS DISTINCT FROM m.ps)
   AND pe.status NOT IN ('project','completed','sold','closed','legal_review','claim_filed','claim_approved','capped_out');
