-- Seed 20 AccuLynx / JobNimbus-style automations into every tenant.
-- Idempotent: skips automations whose name already exists for that tenant.

WITH automation_templates(name, description, trigger_type, trigger_conditions, actions) AS (
  VALUES
  ('New Lead Welcome SMS',
   'Instantly text every new lead so they know you received their request.',
   'lead_created', '[]'::jsonb,
   '[{"type":"send_sms","params":{"recipient_type":"homeowner","message":"Hi {{contact.first_name}}, this is {{tenant.name}}. Thanks for reaching out about your roof — a specialist will call you shortly. Reply STOP to opt out."}}]'::jsonb),
  ('New Lead Welcome Email',
   'Send a branded welcome email when a new lead is created.',
   'lead_created', '[]'::jsonb,
   '[{"type":"send_email","params":{"recipient_type":"homeowner","subject":"Welcome to {{tenant.name}}, {{contact.first_name}}","body":"Hi {{contact.first_name}},\n\nThanks for contacting {{tenant.name}}. A licensed inspector will be in touch within one business day to schedule your free roof evaluation.\n\n— The {{tenant.name}} Team"}}]'::jsonb),
  ('Notify Sales Rep of New Lead',
   'Create a follow-up task for the assigned sales rep on every new lead.',
   'lead_created', '[]'::jsonb,
   '[{"type":"assign_task","params":{"assignee_type":"sales_rep","title":"Call new lead: {{contact.full_name}}","description":"Lead source: {{lead.source}} — Address: {{contact.address}}\nPhone: {{contact.phone}}","due_in_minutes":30,"priority":"high"}}]'::jsonb),
  ('Appointment Confirmation SMS',
   'Confirm new appointments by text the moment they are booked.',
   'appointment_scheduled', '[]'::jsonb,
   '[{"type":"send_sms","params":{"recipient_type":"homeowner","message":"You''re confirmed for {{appointment.date}} at {{appointment.time}} with {{appointment.rep_name}} from {{tenant.name}}. Reply RESCHEDULE if you need to change."}}]'::jsonb),
  ('Appointment 24h Reminder',
   'Send a reminder text 24 hours before the appointment window.',
   'appointment_scheduled', '[]'::jsonb,
   '[{"type":"send_sms","params":{"recipient_type":"homeowner","delay_hours":24,"message":"Reminder: {{appointment.rep_name}} from {{tenant.name}} is scheduled for {{appointment.date}} at {{appointment.time}}. See you soon!"}}]'::jsonb),
  ('Inspection Stage — Notify PM',
   'When a lead moves to the Inspection stage, alert the project manager.',
   'pipeline_stage_changed', '[{"field":"stage","operator":"eq","value":"Inspection"}]'::jsonb,
   '[{"type":"assign_task","params":{"assignee_type":"project_manager","title":"Schedule inspection: {{contact.full_name}}","description":"Confirm inspection date and assign field tech.","due_in_minutes":1440,"priority":"medium"}}]'::jsonb),
  ('Inspection Complete Follow-up',
   'Email the homeowner a summary after inspection is marked complete.',
   'job_milestone_changed', '[{"field":"milestone","operator":"eq","value":"inspection_complete"}]'::jsonb,
   '[{"type":"send_email","params":{"recipient_type":"homeowner","subject":"Your roof inspection is complete","body":"Hi {{contact.first_name}},\n\nThanks for letting {{tenant.name}} inspect your roof today. Your detailed report and recommended scope of work will arrive within 24 hours.\n\nQuestions? Reply to this email anytime."}}]'::jsonb),
  ('Estimate Sent — Notify Homeowner',
   'Email the homeowner the moment an estimate is sent.',
   'contract_sent', '[{"field":"document_type","operator":"eq","value":"estimate"}]'::jsonb,
   '[{"type":"send_email","params":{"recipient_type":"homeowner","subject":"Your estimate from {{tenant.name}} is ready","body":"Hi {{contact.first_name}},\n\nYour roofing estimate is ready to review and sign online: {{document.link}}\n\nReply with any questions — we''re happy to walk through it."}}]'::jsonb),
  ('Estimate Follow-up Day 3',
   'SMS follow-up 3 days after an estimate is sent if not yet signed.',
   'contract_sent', '[{"field":"document_type","operator":"eq","value":"estimate"}]'::jsonb,
   '[{"type":"send_sms","params":{"recipient_type":"homeowner","delay_hours":72,"message":"Hi {{contact.first_name}}, just checking in on your estimate from {{tenant.name}}. Any questions I can answer?"}}]'::jsonb),
  ('Contract Signed Celebration',
   'Thank the homeowner immediately after they sign.',
   'contract_signed', '[]'::jsonb,
   '[{"type":"send_email","params":{"recipient_type":"homeowner","subject":"Welcome aboard, {{contact.first_name}}!","body":"Thanks for choosing {{tenant.name}}. Your project manager will reach out within 1 business day to confirm scheduling and material colors."}}]'::jsonb),
  ('Production Kickoff Task',
   'When a contract is signed, create a kickoff task for the PM.',
   'contract_signed', '[]'::jsonb,
   '[{"type":"assign_task","params":{"assignee_type":"project_manager","title":"Production kickoff: {{contact.full_name}}","description":"Order materials, schedule install, send pre-production checklist.","due_in_minutes":2880,"priority":"high"}}]'::jsonb),
  ('Materials Ordered — Notify Customer',
   'Tell the homeowner when materials have been ordered.',
   'job_milestone_changed', '[{"field":"milestone","operator":"eq","value":"materials_ordered"}]'::jsonb,
   '[{"type":"send_sms","params":{"recipient_type":"homeowner","message":"Good news {{contact.first_name}} — your materials have been ordered. We''ll text again once an install date is locked in."}}]'::jsonb),
  ('Pre-Production Call Reminder',
   'Reminds the PM to make a pre-install courtesy call.',
   'job_milestone_changed', '[{"field":"milestone","operator":"eq","value":"production_scheduled"}]'::jsonb,
   '[{"type":"assign_task","params":{"assignee_type":"project_manager","title":"Pre-production call: {{contact.full_name}}","description":"Confirm crew arrival window, parking, pets, and material delivery.","due_in_minutes":2880,"priority":"medium"}}]'::jsonb),
  ('Day-Before-Install SMS',
   'Texts the homeowner the day before install.',
   'job_milestone_changed', '[{"field":"milestone","operator":"eq","value":"install_scheduled"}]'::jsonb,
   '[{"type":"send_sms","params":{"recipient_type":"homeowner","message":"Hi {{contact.first_name}}, our crew arrives tomorrow between 7–8 AM. Please move vehicles from the driveway and secure pets. — {{tenant.name}}"}}]'::jsonb),
  ('Install Complete Thank You',
   'Email a thank-you message after install is marked complete.',
   'job_milestone_changed', '[{"field":"milestone","operator":"eq","value":"install_complete"}]'::jsonb,
   '[{"type":"send_email","params":{"recipient_type":"homeowner","subject":"Your new roof is installed!","body":"Hi {{contact.first_name}},\n\nThank you for trusting {{tenant.name}} with your home. Your final invoice and warranty packet will arrive shortly.\n\nWe''d love a quick review if you''re happy with the work!"}}]'::jsonb),
  ('Auto Final Invoice + Payment Link',
   'Generate the final invoice and a payment link the moment install completes.',
   'job_milestone_changed', '[{"field":"milestone","operator":"eq","value":"install_complete"}]'::jsonb,
   '[{"type":"push_doc","params":{"document_type":"final_invoice","recipient_type":"homeowner"}},{"type":"create_payment_link","params":{"amount_source":"invoice_balance","recipient_type":"homeowner","send_via":"email_and_sms"}}]'::jsonb),
  ('Payment Received Receipt',
   'Email a receipt the moment a payment is received.',
   'payment_received', '[]'::jsonb,
   '[{"type":"send_email","params":{"recipient_type":"homeowner","subject":"Payment received — thank you!","body":"Hi {{contact.first_name}}, we''ve received your payment of {{payment.amount}}. A receipt is attached for your records.\n\n— {{tenant.name}}"}}]'::jsonb),
  ('Balance Reminder — 7 Days',
   'SMS the homeowner if a final balance remains 7 days after install.',
   'job_milestone_changed', '[{"field":"milestone","operator":"eq","value":"install_complete"}]'::jsonb,
   '[{"type":"send_sms","params":{"recipient_type":"homeowner","delay_hours":168,"message":"Hi {{contact.first_name}}, friendly reminder that your final balance with {{tenant.name}} is still open. Pay online: {{invoice.link}}"}}]'::jsonb),
  ('Review Request Post-Project',
   'Ask for a Google review once the project closes.',
   'job_milestone_changed', '[{"field":"milestone","operator":"eq","value":"project_complete"}]'::jsonb,
   '[{"type":"send_email","params":{"recipient_type":"homeowner","subject":"Quick favor, {{contact.first_name}}?","body":"If you''re happy with your new roof, would you mind leaving us a quick review? It means the world to our small team.\n\n{{tenant.review_link}}\n\n— {{tenant.name}}"}},{"type":"send_sms","params":{"recipient_type":"homeowner","delay_hours":24,"message":"Hi {{contact.first_name}} — would you mind leaving {{tenant.name}} a quick review? {{tenant.review_link}}"}}]'::jsonb),
  ('Lost Lead Win-Back (30 days)',
   'Re-engage leads marked Lost or Cold after 30 days.',
   'lead_status_changed', '[{"field":"status","operator":"in","value":["lost","cold"]}]'::jsonb,
   '[{"type":"send_email","params":{"recipient_type":"homeowner","delay_hours":720,"subject":"Still thinking about your roof, {{contact.first_name}}?","body":"It''s been a few weeks since we last spoke. If you''re still considering a roof project, {{tenant.name}} is offering complimentary re-inspections this month — just reply YES."}}]'::jsonb)
)
INSERT INTO public.automations (tenant_id, name, description, trigger_type, trigger_conditions, actions, is_active)
SELECT t.id, a.name, a.description, a.trigger_type, a.trigger_conditions, a.actions, true
FROM public.tenants t
CROSS JOIN automation_templates a
WHERE NOT EXISTS (
  SELECT 1 FROM public.automations existing
  WHERE existing.tenant_id = t.id AND existing.name = a.name
);