// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSupabaseFetch } from '@/lib/apiInterceptor';

const SUPABASE_URL = "https://alxelfrbjzkmtnsulcei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFseGVsZnJianprbXRuc3VsY2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTYyNzcsImV4cCI6MjA3MzczMjI3N30.ouuzXBD8iercLbbxtueioRppHsywgpgxEdDqt6AaMtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: The generated `Database` types in ./types.ts are out of sync with the live
// schema for several tables (missing tenant_id, renamed columns, etc.) and that file
// is auto-managed and cannot be hand-edited. Until types are regenerated, we keep
// the runtime client typed with Database for read paths but cast the export to a
// loosely-typed client so insert/update payloads aren't rejected as `never`.
const _client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: createSupabaseFetch()
  }
});

export const supabase = _client as typeof _client & {
  from: (table: string) => any;
};