// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createSupabaseFetch } from '@/lib/apiInterceptor';

const SUPABASE_URL = "https://alxelfrbjzkmtnsulcei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFseGVsZnJianprbXRuc3VsY2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNTYyNzcsImV4cCI6MjA3MzczMjI3N30.ouuzXBD8iercLbbxtueioRppHsywgpgxEdDqt6AaMtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: The generated `Database` types in ./types.ts are out of sync with the live
// schema for several tables (missing tenant_id, renamed columns, etc.) and that
// file is auto-managed and cannot be hand-edited. Until types are regenerated, we
// expose the client with a loose `from()` signature so insert/update payloads are
// not rejected as `never`. Read paths still work the same at runtime.
const _client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: createSupabaseFetch()
  }
});

type LooseSupabase = Omit<typeof _client, 'from'> & {
  from: (table: string) => any;
};

export const supabase: LooseSupabase = _client as unknown as LooseSupabase;